// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.security;

import com.klu.entity.User;
import com.klu.repository.UserRepository;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

/**
 * Loads a {@link User} from the database using their email address.
 * Email is the unique login credential in this application.
 */
@Service
public class CustomUserDetailsService implements UserDetailsService {
    private final UserRepository userRepository;

    /**
     * Spring Security calls this with whatever was entered in the "username"
     * field — in our case that field carries the email address.
     */
    @Override
    @Transactional(readOnly = true)
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        User user = userRepository.findByEmail(email).orElseThrow(() -> new UsernameNotFoundException("No user found with email: " + email));
        return  // email acts as the Security principal
        org.springframework.security.core.userdetails.User.builder().username(user.getEmail()).password(user.getPassword()).authorities(List.of(new SimpleGrantedAuthority("ROLE_" + user.getRole().name()))).accountExpired(false).accountLocked(false).credentialsExpired(false).disabled(!user.isEnabled()).build();
    }

    public CustomUserDetailsService(final UserRepository userRepository) {
        this.userRepository = userRepository;
    }
}
