// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.security;

import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.UnsupportedJwtException;
import io.jsonwebtoken.security.SignatureException;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import java.io.IOException;

/**
 * Intercepts every HTTP request exactly once, extracts the JWT from the
 * {@code Authorization: Bearer <token>} header, validates it, and —
 * if valid — sets the authenticated principal in the SecurityContext.
 *
 * <p>Invalid / expired tokens are rejected with a 401 JSON response
 * before the request reaches any controller.
 */
@Component
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(JwtAuthenticationFilter.class);
    private final JwtUtil jwtUtil;
    private final CustomUserDetailsService userDetailsService;

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        final String authHeader = request.getHeader("Authorization");
        // ── No Bearer token present → continue chain (public routes handled by SecurityConfig) ──
        if (authHeader == null || !authHeader.startsWith("Bearer ")) {
            filterChain.doFilter(request, response);
            return;
        }
        final String jwt = authHeader.substring(7); // strip "Bearer "
        try {
            final String email = jwtUtil.extractEmail(jwt);
            // Only authenticate if email extracted AND SecurityContext not already populated
            if (email != null && SecurityContextHolder.getContext().getAuthentication() == null) {
                UserDetails userDetails = userDetailsService.loadUserByUsername(email);
                if (jwtUtil.isTokenValid(jwt, userDetails)) {
                    UsernamePasswordAuthenticationToken authToken = new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
                    authToken.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                    SecurityContextHolder.getContext().setAuthentication(authToken);
                    log.debug("Authenticated user \'{}\' via JWT", email);
                }
            }
            filterChain.doFilter(request, response);
        } catch (ExpiredJwtException ex) {
            log.warn("JWT expired for request [{}]: {}", request.getRequestURI(), ex.getMessage());
            sendError(response, HttpStatus.UNAUTHORIZED, "JWT token has expired. Please log in again.");
        } catch (SignatureException | MalformedJwtException | UnsupportedJwtException ex) {
            log.warn("Invalid JWT for request [{}]: {}", request.getRequestURI(), ex.getMessage());
            sendError(response, HttpStatus.UNAUTHORIZED, "Invalid JWT token.");
        } catch (UsernameNotFoundException ex) {
            log.warn("User not found while validating JWT: {}", ex.getMessage());
            sendError(response, HttpStatus.UNAUTHORIZED, "User account not found.");
        } catch (Exception ex) {
            log.error("Unexpected error during JWT validation: {}", ex.getMessage(), ex);
            sendError(response, HttpStatus.INTERNAL_SERVER_ERROR, "An authentication error occurred.");
        }
    }

    // ── Helper: write a JSON error body without using Jackson ──────────────────
    private void sendError(HttpServletResponse response, HttpStatus status, String message) throws IOException {
        response.setStatus(status.value());
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        response.getWriter().write("{\"success\":false,\"status\":%d,\"error\":\"%s\",\"message\":\"%s\"}".formatted(status.value(), status.getReasonPhrase(), message));
    }

    public JwtAuthenticationFilter(final JwtUtil jwtUtil, final CustomUserDetailsService userDetailsService) {
        this.jwtUtil = jwtUtil;
        this.userDetailsService = userDetailsService;
    }
}
