// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.security;

import io.jsonwebtoken.*;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;
import javax.crypto.SecretKey;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * JWT utility component responsible for:
 * <ul>
 *   <li>Generating signed JWT tokens</li>
 *   <li>Validating tokens against a UserDetails principal</li>
 *   <li>Extracting claims (email / role / expiration)</li>
 * </ul>
 *
 * <p>Algorithm : HMAC-SHA256 (HS256) via JJWT 0.12.x
 * <p>Principal  : user's email address
 */
@Component
public class JwtUtil {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(JwtUtil.class);
    @Value("${app.jwt.secret}")
    private String jwtSecret;
    @Value("${app.jwt.expiration-ms}")
    private long jwtExpirationMs;

    // ================================================================
    //  Token Generation
    // ================================================================
    /**
     * Creates a signed JWT for the given {@link UserDetails}.
     * The token subject is the user's email.
     * An extra {@code "role"} claim stores the first granted authority.
     *
     * @param userDetails Spring Security principal
     * @return compact, signed JWT string
     */
    public String generateToken(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("role", userDetails.getAuthorities().iterator().next().getAuthority());
        return buildToken(claims, userDetails.getUsername()); // username = email
    }

    private String buildToken(Map<String, Object> extraClaims, String subject) {
        long now = System.currentTimeMillis();
        return Jwts.builder().claims(extraClaims).subject(subject).issuedAt(new Date(now)).expiration(new Date(now + jwtExpirationMs)).signWith(getSigningKey()).compact();
    }

    // ================================================================
    //  Token Validation
    // ================================================================
    /**
     * Validates the token against the stored UserDetails.
     * Checks: subject matches principal AND token is not expired.
     *
     * @param token       raw JWT string (without "Bearer " prefix)
     * @param userDetails loaded from DB
     * @return true if valid
     */
    public boolean isTokenValid(String token, UserDetails userDetails) {
        final String email = extractEmail(token);
        return email.equals(userDetails.getUsername()) && !isTokenExpired(token);
    }

    private boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    // ================================================================
    //  Claims Extraction
    // ================================================================
    /**
     * Extract the email (subject) from the token.
     */
    public String extractEmail(String token) {
        return extractClaim(token, Claims::getSubject);
    }

    /**
     * Extract the role claim (e.g. "ROLE_ADMIN") from the token.
     */
    public String extractRole(String token) {
        return extractClaim(token, claims -> claims.get("role", String.class));
    }

    /**
     * Extract the issued-at timestamp.
     */
    public Date extractIssuedAt(String token) {
        return extractClaim(token, Claims::getIssuedAt);
    }

    /**
     * Extract the expiration timestamp.
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Generic claims extractor – applies {@code claimsResolver} to the full claims map.
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        return claimsResolver.apply(extractAllClaims(token));
    }

    private Claims extractAllClaims(String token) {
        return Jwts.parser().verifyWith(getSigningKey()).build().parseSignedClaims(token).getPayload();
    }

    // ================================================================
    //  Helpers
    // ================================================================
    /**
     * Configured expiration in milliseconds (for response metadata).
     */
    public long getExpirationMs() {
        return jwtExpirationMs;
    }

    private SecretKey getSigningKey() {
        byte[] keyBytes = Decoders.BASE64.decode(jwtSecret);
        return Keys.hmacShaKeyFor(keyBytes);
    }
}
