// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.security;

import jakarta.servlet.http.HttpServletResponse;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.AuthenticationProvider;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
import java.util.List;

@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {
    private final JwtAuthenticationFilter jwtAuthenticationFilter;
    private final CustomUserDetailsService userDetailsService;

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        
        // ── 1. Public (no token required) ─────────────────────────
        // ── 2. Identity probe — any valid token ───────────────────
        // ── 3. FUND MANAGEMENT (ADMIN only — write) ───────────────
        //    ADMIN can create, update, soft-delete funds
        // ── 4. FUND READ — all four roles ─────────────────────────
        //    Everyone needs to browse/search funds
        // ── 5. INVESTMENTS — INVESTOR (own portfolio) + ADMIN ─────
        //    Only investors place, view, and redeem investments.
        //    ADMIN can also read/manage any investment.
        // ── 6. ANALYTICS — ANALYST (primary) + ADMIN + ADVISOR ───
        //    ANALYST owns analytics; ADMIN always has full access;
        //    ADVISOR can read analytics to inform recommendations;
        //    INVESTOR may view their own monthly report.
        // ── 7. RECOMMENDATIONS — ADVISOR (primary) + ADMIN ────────
        //    Only advisors post recommendations; ADMIN can manage them.
        // ── 8. USER MANAGEMENT — ADMIN only ──────────────────────
        // ── 9. Catch-all: any remaining endpoint needs a valid token
        http.cors(cors -> cors.configurationSource(corsConfigurationSource())).csrf(AbstractHttpConfigurer::disable).exceptionHandling(ex -> ex.authenticationEntryPoint((req, res, authException) -> {
            res.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            res.setContentType("application/json");
            res.getWriter().write("{\"error\":\"Unauthorized\",\"message\":\"" + authException.getMessage() + "\"}");
        }).accessDeniedHandler((req, res, accessDeniedException) -> {
            res.setStatus(HttpServletResponse.SC_FORBIDDEN);
            res.setContentType("application/json");
            res.getWriter().write("{\"error\":\"Forbidden\",\"message\":\"Access denied\"}");
        })).sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(auth -> auth.requestMatchers("/api/auth/register", "/api/auth/login","/api/funds/**").permitAll().requestMatchers("/api/auth/me").permitAll().requestMatchers(HttpMethod.POST, "/api/funds/**").hasRole("ADMIN").requestMatchers(HttpMethod.PUT, "/api/funds/**").hasRole("ADMIN").requestMatchers(HttpMethod.DELETE, "/api/funds/**").hasRole("ADMIN").requestMatchers("/api/investments/**").hasAnyRole("INVESTOR", "ADMIN").requestMatchers("/api/analytics/**").hasAnyRole("ANALYST", "ADMIN", "ADVISOR", "INVESTOR").requestMatchers("/api/recommendations/**").hasAnyRole("ADVISOR", "ADMIN").requestMatchers("/api/users/**").hasRole("ADMIN").anyRequest().authenticated()).authenticationProvider(authenticationProvider()).addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class);
        return http.build();
    }

    @Bean
    public AuthenticationProvider authenticationProvider() {
        DaoAuthenticationProvider provider = new DaoAuthenticationProvider();
        provider.setUserDetailsService(userDetailsService);
        provider.setPasswordEncoder(passwordEncoder());
        return provider;
    }

    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception {
        return config.getAuthenticationManager();
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Bean
    public CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowedOriginPatterns(List.of("*"));
        config.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"));
        config.setAllowedHeaders(List.of("*"));
        config.setAllowCredentials(true);
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", config);
        return source;
    }

    public SecurityConfig(final JwtAuthenticationFilter jwtAuthenticationFilter, final CustomUserDetailsService userDetailsService) {
        this.jwtAuthenticationFilter = jwtAuthenticationFilter;
        this.userDetailsService = userDetailsService;
    }
}
