// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.controller;

import com.klu.dto.ApiResponse;
import com.klu.dto.AuthResponseDTO;
import com.klu.dto.LoginRequestDTO;
import com.klu.dto.RegisterRequestDTO;
import com.klu.service.AuthService;
import com.klu.util.SecurityUtil;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller for JWT-based authentication.
 *
 * Base URL : /api/auth   (fully public — no token required)
 *
 * ┌─────────────────────────────────────────────────────────────────┐
 * │  POST /api/auth/register  →  create account + get JWT          │
 * │  POST /api/auth/login     →  verify credentials + get JWT      │
 * │  GET  /api/auth/me        →  return current principal's email   │
 * └─────────────────────────────────────────────────────────────────┘
 *
 * The JWT returned must be used in subsequent requests as:
 *   Authorization: Bearer <token>
 */
@RestController
@RequestMapping("/api/auth")
public class AuthController {
    private final AuthService authService;

    // ================================================================
    //  REGISTER
    // ================================================================
    /**
     * Register a new user account.
     *
     * <p>Request body:
     * <pre>
     * {
     *   "name":     "John Smith",
     *   "email":    "john@example.com",
     *   "password": "mySecret123",
     *   "role":     "INVESTOR"        // optional: ADMIN|INVESTOR|ADVISOR|ANALYST
     * }
     * </pre>
     *
     * <p>Response (201 Created):
     * <pre>
     * {
     *   "success": true,
     *   "message": "Account created successfully",
     *   "data": {
     *     "token":     "eyJhbGci...",
     *     "tokenType": "Bearer",
     *     "name":      "John Smith",
     *     "email":     "john@example.com",
     *     "role":      "INVESTOR",
     *     "userId":    1
     *   }
     * }
     * </pre>
     */
    @PostMapping("/register")
    public ResponseEntity<ApiResponse<AuthResponseDTO>> register(@RequestBody RegisterRequestDTO request) {
        AuthResponseDTO response = authService.register(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok("Account created successfully", response));
    }

    // ================================================================
    //  LOGIN
    // ================================================================
    /**
     * Authenticate with email + password, receive a JWT.
     *
     * <p>Request body:
     * <pre>
     * {
     *   "email":    "john@example.com",
     *   "password": "mySecret123"
     * }
     * </pre>
     *
     * <p>Response (200 OK):
     * <pre>
     * {
     *   "success": true,
     *   "message": "Login successful",
     *   "data": {
     *     "token":     "eyJhbGci...",
     *     "tokenType": "Bearer",
     *     "name":      "John Smith",
     *     "email":     "john@example.com",
     *     "role":      "INVESTOR",
     *     "userId":    1
     *   }
     * }
     * </pre>
     */
    @PostMapping("/login")
    public ResponseEntity<ApiResponse<AuthResponseDTO>> login(@RequestBody LoginRequestDTO request) {
        AuthResponseDTO response = authService.login(request);
        return ResponseEntity.ok(ApiResponse.ok("Login successful", response));
    }

    // ================================================================
    //  ME  (identity probe — requires a valid token)
    // ================================================================
    /**
     * Returns the email of the currently authenticated user.
     * Useful as a token validity check from the frontend.
     *
     * <p>Header required: {@code Authorization: Bearer <token>}
     *
     * <p>Response (200 OK):
     * <pre>{ "success": true, "message": "OK", "data": "john@example.com" }</pre>
     */
    @GetMapping("/me")
    public ResponseEntity<ApiResponse<String>> me() {
        String email = SecurityUtil.getCurrentUsername(); // returns email (the principal)
        return ResponseEntity.ok(ApiResponse.ok("Current principal", email));
    }

    public AuthController(final AuthService authService) {
        this.authService = authService;
    }
}
