// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.controller;

import com.klu.dto.ApiResponse;
import com.klu.dto.InvestmentRequestDTO;
import com.klu.dto.InvestmentResponseDTO;
import com.klu.dto.TotalInvestmentDTO;
import com.klu.service.InvestmentService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.List;

/**
 * REST controller for Investment operations.
 *
 * Base URL : /api/investments
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Method  │  URL                                   │  Description         │
 * ├──────────┼────────────────────────────────────────┼──────────────────────┤
 * │  POST    │  /api/investments                      │  Invest in a fund    │
 * │  GET     │  /api/investments/user/{userId}        │  Get user investments│
 * │  GET     │  /api/investments/user/{userId}/active │  Active only         │
 * │  GET     │  /api/investments/user/{userId}/total  │  Total summary       │
 * │  GET     │  /api/investments/user/{userId}/fund/{fId} │  By fund         │
 * │  PUT     │  /api/investments/{id}/redeem          │  Redeem investment   │
 * └──────────┴────────────────────────────────────────┴──────────────────────┘
 */
@RestController
@RequestMapping("/api/investments")
public class InvestmentController {
    private final InvestmentService investmentService;

    // ================================================================
    //  1. INVEST IN A FUND
    // ================================================================
    /**
     * Place a new investment (Lump-Sum or SIP).
     *
     * <p>Request body:
     * <pre>
     * {
     *   "userId": 1,
     *   "fundId": 3,
     *   "amount": 10000.00,
     *   "type":   "LUMP_SUM"
     * }
     * </pre>
     *
     * <p>Response (201 Created):
     * <pre>
     * {
     *   "success": true,
     *   "message": "Investment placed successfully",
     *   "data": {
     *     "id": 1,
     *     "userId": 1, "fundId": 3, "amount": 10000.00,
     *     "date": "2026-03-31", "units": 221.2890, ...
     *   }
     * }
     * </pre>
     */
    @PostMapping
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<InvestmentResponseDTO>> invest(@RequestBody InvestmentRequestDTO request) {
        InvestmentResponseDTO result = investmentService.invest(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok("Investment placed successfully", result));
    }

    // ================================================================
    //  2. GET USER INVESTMENTS
    // ================================================================
    /**
     * Get ALL investments for a user (any status).
     *
     * @param userId the User ID
     */
    @GetMapping("/user/{userId}")
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<List<InvestmentResponseDTO>>> getUserInvestments(@PathVariable Long userId) {
        return ResponseEntity.ok(ApiResponse.ok("Investments for user " + userId, investmentService.getUserInvestments(userId)));
    }

    /**
     * Get only ACTIVE investments for a user.
     *
     * @param userId the User ID
     */
    @GetMapping("/user/{userId}/active")
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<List<InvestmentResponseDTO>>> getActiveUserInvestments(@PathVariable Long userId) {
        return ResponseEntity.ok(ApiResponse.ok("Active investments for user " + userId, investmentService.getActiveUserInvestments(userId)));
    }

    /**
     * Get investments for a user in a specific fund.
     *
     * @param userId the User ID
     * @param fundId the Fund ID
     */
    @GetMapping("/user/{userId}/fund/{fundId}")
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<List<InvestmentResponseDTO>>> getUserInvestmentsByFund(@PathVariable Long userId, @PathVariable Long fundId) {
        return ResponseEntity.ok(ApiResponse.ok("Investments for user " + userId + " in fund " + fundId, investmentService.getUserInvestmentsByFund(userId, fundId)));
    }

    // ================================================================
    //  3. CALCULATE TOTAL INVESTMENT
    // ================================================================
    /**
     * Calculate the complete investment summary for a user:
     * <ul>
     *   <li>Total active invested amount</li>
     *   <li>Grand total (all statuses)</li>
     *   <li>Current portfolio market value</li>
     *   <li>Overall gain / loss (INR + %)</li>
     *   <li>Number of distinct funds</li>
     *   <li>Total transaction count</li>
     * </ul>
     *
     * @param userId the User ID
     */
    @GetMapping("/user/{userId}/total")
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<TotalInvestmentDTO>> calculateTotal(@PathVariable Long userId) {
        return ResponseEntity.ok(ApiResponse.ok("Total investment summary", investmentService.calculateTotalInvestment(userId)));
    }

    // ================================================================
    //  REDEEM
    // ================================================================
    /**
     * Redeem an ACTIVE investment — changes status to REDEEMED.
     *
     * @param id the Investment ID
     */
    @PutMapping("/{id}/redeem")
    @PreAuthorize("hasAnyRole(\'INVESTOR\', \'ADMIN\')")
    public ResponseEntity<ApiResponse<InvestmentResponseDTO>> redeem(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.ok("Investment redeemed successfully", investmentService.redeem(id)));
    }

    public InvestmentController(final InvestmentService investmentService) {
        this.investmentService = investmentService;
    }
}
