// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.controller;

import com.klu.dto.ApiResponse;
import com.klu.dto.RecommendationDTO;
import com.klu.service.RecommendationService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.List;

/**
 * REST controller for ADVISOR Recommendation APIs.
 *
 * Base URL : /api/recommendations
 *
 * ┌───────────────────────────────────────────────────────────────────────────┐
 * │ Method │ URL                                              │ Roles         │
 * ├────────┼──────────────────────────────────────────────────┼───────────────┤
 * │ GET    │ /api/recommendations/top-buys?advisorId=1        │ ADVISOR,ADMIN │
 * │ GET    │ /api/recommendations/top-buys?limit=5            │ ADVISOR,ADMIN │
 * │ GET    │ /api/recommendations/by-risk?riskLevel=MODERATE  │ ADVISOR,ADMIN │
 * │ GET    │ /api/recommendations/by-category?category=EQUITY │ ADVISOR,ADMIN │
 * │ POST   │ /api/recommendations/custom                      │ ADVISOR,ADMIN │
 * └───────────────────────────────────────────────────────────────────────────┘
 *
 * Filter-chain rule: /api/recommendations/** → ADVISOR | ADMIN
 * Method-level @PreAuthorize provides a second, explicit layer.
 */
@RestController
@RequestMapping("/api/recommendations")
public class RecommendationController {
    private final RecommendationService recommendationService;

    // ================================================================
    //  1. TOP BUY OPPORTUNITIES
    // ================================================================
    /**
     * Returns the top-N active funds ranked by annualised returns —
     * the advisor's "hot picks" for BUY recommendations.
     *
     * <p>Query params:
     * <ul>
     *   <li>{@code advisorId} — the ADVISOR user's ID (required)</li>
     *   <li>{@code limit}     — number of results (default 10, max 50)</li>
     * </ul>
     *
     * <p>Example:
     * <pre>GET /api/recommendations/top-buys?advisorId=2&limit=5</pre>
     *
     * <p>Response 200:
     * <pre>
     * {
     *   "success": true,
     *   "message": "Top BUY opportunities",
     *   "data": [
     *     { "fundId": 3, "fundName": "Quant Small Cap", "action": "BUY",
     *       "returns": 28.40, "riskLevel": "VERY_HIGH", ... },
     *     ...
     *   ]
     * }
     * </pre>
     */
    @GetMapping("/top-buys")
    @PreAuthorize("hasAnyRole(\'ADVISOR\',\'ADMIN\')")
    public ResponseEntity<ApiResponse<List<RecommendationDTO>>> getTopBuys(@RequestParam Long advisorId, @RequestParam(defaultValue = "10") int limit) {
        if (limit < 1) limit = 1;
        if (limit > 50) limit = 50;
        List<RecommendationDTO> recs = recommendationService.getTopBuyOpportunities(advisorId, limit);
        return ResponseEntity.ok(ApiResponse.ok("Top BUY opportunities", recs));
    }

    // ================================================================
    //  2. RECOMMENDATIONS BY RISK LEVEL
    // ================================================================
    /**
     * Returns recommendations filtered to a specific risk level.
     * BUY action is suggested for LOW–MODERATE; SELL (caution) for HIGH–VERY_HIGH.
     *
     * <p>Query params:
     * <ul>
     *   <li>{@code advisorId} — the ADVISOR user's ID (required)</li>
     *   <li>{@code riskLevel}  — LOW | MODERATE | HIGH | VERY_HIGH</li>
     * </ul>
     *
     * <p>Example:
     * <pre>GET /api/recommendations/by-risk?advisorId=2&riskLevel=MODERATE</pre>
     */
    @GetMapping("/by-risk")
    @PreAuthorize("hasAnyRole(\'ADVISOR\',\'ADMIN\')")
    public ResponseEntity<ApiResponse<List<RecommendationDTO>>> getByRisk(@RequestParam Long advisorId, @RequestParam String riskLevel) {
        List<RecommendationDTO> recs = recommendationService.getRecommendationsByRisk(advisorId, riskLevel);
        return ResponseEntity.ok(ApiResponse.ok("Recommendations for risk level: " + riskLevel.toUpperCase(), recs));
    }

    // ================================================================
    //  3. RECOMMENDATIONS BY CATEGORY
    // ================================================================
    /**
     * Returns fund recommendations filtered to a specific category.
     *
     * <p>Query params:
     * <ul>
     *   <li>{@code advisorId} — the ADVISOR user's ID (required)</li>
     *   <li>{@code category}  — EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX</li>
     * </ul>
     *
     * <p>Example:
     * <pre>GET /api/recommendations/by-category?advisorId=2&category=EQUITY</pre>
     */
    @GetMapping("/by-category")
    @PreAuthorize("hasAnyRole(\'ADVISOR\',\'ADMIN\')")
    public ResponseEntity<ApiResponse<List<RecommendationDTO>>> getByCategory(@RequestParam Long advisorId, @RequestParam String category) {
        List<RecommendationDTO> recs = recommendationService.getRecommendationsByCategory(advisorId, category);
        return ResponseEntity.ok(ApiResponse.ok("Recommendations for category: " + category.toUpperCase(), recs));
    }

    // ================================================================
    //  4. CUSTOM RECOMMENDATION FOR A SPECIFIC FUND
    // ================================================================
    /**
     * Posts a fully custom recommendation for a specific fund.
     *
     * <p>Request body:
     * <pre>
     * {
     *   "advisorId": 2,
     *   "fundId":    5,
     *   "action":    "BUY",
     *   "rationale": "Strong recent NAV growth and consistent 3-year returns."
     * }
     * </pre>
     *
     * <p>Response 201 Created:
     * <pre>
     * {
     *   "success": true,
     *   "message": "Recommendation created",
     *   "data": { "fundId": 5, "action": "BUY", "advisorName": "Jane Doe", ... }
     * }
     * </pre>
     */
    @PostMapping("/custom")
    @PreAuthorize("hasAnyRole(\'ADVISOR\',\'ADMIN\')")
    public ResponseEntity<ApiResponse<RecommendationDTO>> createCustomRecommendation(@RequestBody CustomRecommendationRequest req) {
        RecommendationDTO rec = recommendationService.createRecommendation(req.advisorId(), req.fundId(), req.action(), req.rationale());
        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok("Recommendation created", rec));
    }

    // ---- Inner request record ----
    public record CustomRecommendationRequest(Long advisorId, Long fundId, String action, String rationale) {
    }

    public RecommendationController(final RecommendationService recommendationService) {
        this.recommendationService = recommendationService;
    }
}
