// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.service;

import com.klu.dto.MonthlyReportDTO;
import com.klu.dto.RiskReturnDTO;
import com.klu.dto.TopFundDTO;
import com.klu.entity.MutualFund;
import com.klu.exception.ResourceNotFoundException;
import com.klu.repository.InvestmentRepository;
import com.klu.repository.MonthlyInvestmentProjection;
import com.klu.repository.MutualFundRepository;
import com.klu.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Month;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Service for the three Analytics APIs:
 *
 *  1. {@link #getTopPerformingFunds}   — Top-N funds ranked by annualised returns + AUM
 *  2. {@link #getRiskVsReturn}         — Risk-bucket comparison matrix
 *  3. {@link #getMonthlyReport}        — Monthly investment report (platform or per-user)
 */
@Service
public class AnalyticsService {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AnalyticsService.class);
    private final MutualFundRepository fundRepository;
    private final InvestmentRepository investmentRepository;
    private final UserRepository userRepository;

    // ================================================================
    //  1. TOP PERFORMING FUNDS
    // ================================================================
    /**
     * Returns the top {@code limit} active funds ranked by:
     * <ol>
     *   <li>Annualised returns (primary — highest first)</li>
     *   <li>Total AUM (secondary — highest first)</li>
     * </ol>
     *
     * Additional metrics per fund: totalInvestors, totalAum, rank.
     *
     * @param limit maximum number of funds to return (default: 10)
     * @return ranked list of {@link TopFundDTO}
     */
    @Transactional(readOnly = true)
    public List<TopFundDTO> getTopPerformingFunds(int limit) {
        log.debug("Analytics: fetching top {} performing funds", limit);
        // Fetch all active funds
        List<MutualFund> activeFunds = fundRepository.findByActiveTrue();
        // Build AUM map  fundId → totalAum
        Map<Long, BigDecimal> aumMap = new HashMap<>();
        for (Object[] row : investmentRepository.getAumByFund()) {
            Long fundId = ((Number) row[0]).longValue();
            BigDecimal totalAum = (BigDecimal) row[1];
            aumMap.put(fundId, totalAum);
        }
        // Build investor-count map  fundId → investorCount
        Map<Long, Long> investorMap = new HashMap<>();
        for (Object[] row : investmentRepository.getInvestorCountByFund()) {
            Long fundId = ((Number) row[0]).longValue();
            Long investorCount = ((Number) row[1]).longValue();
            investorMap.put(fundId, investorCount);
        }
        // Sort funds: returns DESC, then AUM DESC
        activeFunds.sort(Comparator.comparing(MutualFund::getReturns, Comparator.reverseOrder()).thenComparing(f -> aumMap.getOrDefault(f.getId(), BigDecimal.ZERO), Comparator.reverseOrder()));
        // Build ranked DTOs (take top N)
        List<TopFundDTO> result = new ArrayList<>();
        int rank = 1;
        for (MutualFund fund : activeFunds) {
            if (rank > limit) break;
            BigDecimal aum = aumMap.getOrDefault(fund.getId(), BigDecimal.ZERO);
            Long investorCount = investorMap.getOrDefault(fund.getId(), 0L);
            result.add( // Using returns as proxy for NAV growth %
            TopFundDTO.builder().id(fund.getId()).fundName(fund.getFundName()).category(fund.getCategory()).riskLevel(fund.getRiskLevel().name()).returns(fund.getReturns()).nav(fund.getNav()).navGrowth(fund.getReturns()).totalInvestors(investorCount).totalAum(aum.setScale(2, RoundingMode.HALF_UP)).rank(rank).build());
            rank++;
        }
        log.debug("Analytics: returning {} top funds", result.size());
        return result;
    }

    // ================================================================
    //  2. RISK VS RETURN COMPARISON
    // ================================================================
    /**
     * Groups all active funds by their {@link MutualFund.RiskLevel} and computes
     * per-bucket statistics: avg / min / max / median returns, fund count,
     * plus an individual fund breakdown sorted by returns desc.
     *
     * @return one {@link RiskReturnDTO} per risk bucket (ordered LOW → VERY_HIGH)
     */
    @Transactional(readOnly = true)
    public List<RiskReturnDTO> getRiskVsReturn() {
        log.debug("Analytics: building risk-vs-return matrix");
        List<MutualFund> activeFunds = fundRepository.findByActiveTrue();
        // Group by risk level
        Map<MutualFund.RiskLevel, List<MutualFund>> grouped = activeFunds.stream().collect(Collectors.groupingBy(MutualFund::getRiskLevel));
        // Ordered by risk ascending
        List<RiskReturnDTO> result = new ArrayList<>();
        for (MutualFund.RiskLevel level : MutualFund.RiskLevel.values()) {
            List<MutualFund> bucket = grouped.getOrDefault(level, List.of());
            if (bucket.isEmpty()) {
                result.add(RiskReturnDTO.builder().riskLevel(level.name()).fundCount(0).averageReturns(BigDecimal.ZERO).minReturns(BigDecimal.ZERO).maxReturns(BigDecimal.ZERO).medianReturns(BigDecimal.ZERO).funds(List.of()).build());
                continue;
            }
            List<BigDecimal> returnsList = bucket.stream().map(MutualFund::getReturns).sorted().collect(Collectors.toList());
            BigDecimal avg = average(returnsList);
            BigDecimal min = returnsList.get(0);
            BigDecimal max = returnsList.get(returnsList.size() - 1);
            BigDecimal median = median(returnsList);
            // Individual funds — sorted by returns desc
            List<RiskReturnDTO.FundSummary> fundSummaries = bucket.stream().sorted(Comparator.comparing(MutualFund::getReturns).reversed()).map(f -> RiskReturnDTO.FundSummary.builder().id(f.getId()).fundName(f.getFundName()).returns(f.getReturns()).nav(f.getNav()).build()).collect(Collectors.toList());
            result.add(RiskReturnDTO.builder().riskLevel(level.name()).fundCount(bucket.size()).averageReturns(avg).minReturns(min).maxReturns(max).medianReturns(median).funds(fundSummaries).build());
        }
        return result;
    }

    // ================================================================
    //  3. MONTHLY INVESTMENT REPORT
    // ================================================================
    /**
     * Aggregates investments month-by-month for a given calendar year.
     *
     * <p>If {@code userId} is {@code null}, a platform-wide report is returned.
     * Otherwise the report is scoped to the specified user.
     *
     * @param year   the calendar year (e.g. 2026)
     * @param userId optional user ID to scope the report; {@code null} = platform
     * @return {@link MonthlyReportDTO} with per-month entries and period totals
     */
    @Transactional(readOnly = true)
    public MonthlyReportDTO getMonthlyReport(int year, Long userId) {
        log.debug("Analytics: monthly report year={} userId={}", year, userId);
        // Validate user if scoped
        if (userId != null && !userRepository.existsById(userId)) {
            throw new ResourceNotFoundException("User", "id", userId);
        }
        // Fetch projection rows
        List<MonthlyInvestmentProjection> rows = (userId == null) ? investmentRepository.getMonthlyReport(year) : investmentRepository.getMonthlyReportByUser(userId, year);
        // Group projection rows by month number
        Map<Integer, List<MonthlyInvestmentProjection>> byMonth = rows.stream().collect(Collectors.groupingBy(MonthlyInvestmentProjection::getMonth));
        // Build month entries
        List<MonthlyReportDTO.MonthEntry> monthEntries = new ArrayList<>();
        BigDecimal cumulativeTotal = BigDecimal.ZERO;
        BigDecimal periodTotal = BigDecimal.ZERO;
        long periodTxCount = 0;
        Set<String> categoriesInPeriod = new LinkedHashSet<>();
        for (int m = 1; m <= 12; m++) {
            List<MonthlyInvestmentProjection> monthRows = byMonth.getOrDefault(m, List.of());
            if (monthRows.isEmpty()) continue;
            BigDecimal monthTotal = monthRows.stream().map(MonthlyInvestmentProjection::getTotalAmount).reduce(BigDecimal.ZERO, BigDecimal::add).setScale(2, RoundingMode.HALF_UP);
            long monthTxCount = monthRows.stream().mapToLong(r -> r.getTransactionCount() != null ? r.getTransactionCount() : 0).sum();
            BigDecimal monthAvg = monthTxCount > 0 ? monthTotal.divide(BigDecimal.valueOf(monthTxCount), 2, RoundingMode.HALF_UP) : BigDecimal.ZERO;
            cumulativeTotal = cumulativeTotal.add(monthTotal);
            periodTotal = periodTotal.add(monthTotal);
            periodTxCount += monthTxCount;
            // Category breakdown within this month
            List<MonthlyReportDTO.CategoryBreakdown> breakdown = monthRows.stream().filter(r -> r.getCategory() != null).map(r -> {
                categoriesInPeriod.add(r.getCategory());
                return MonthlyReportDTO.CategoryBreakdown.builder().category(r.getCategory()).amount(r.getTotalAmount().setScale(2, RoundingMode.HALF_UP)).transactions(r.getTransactionCount() != null ? r.getTransactionCount() : 0L).build();
            }).collect(Collectors.toList());
            monthEntries.add(MonthlyReportDTO.MonthEntry.builder().month(m).monthName(Month.of(m).getDisplayName(java.time.format.TextStyle.FULL, Locale.ENGLISH)).totalInvested(monthTotal).transactionCount(monthTxCount).averageAmount(monthAvg).cumulativeTotal(cumulativeTotal.setScale(2, RoundingMode.HALF_UP)).categoryBreakdown(breakdown).build());
        }
        String scope = (userId == null) ? "PLATFORM" : "USER:" + userId;
        return MonthlyReportDTO.builder().year(year).reportScope(scope).months(monthEntries).totalInvestedInPeriod(periodTotal.setScale(2, RoundingMode.HALF_UP)).totalTransactionsInPeriod(periodTxCount).activeFundsInPeriod(categoriesInPeriod.size()).build();
    }

    // ================================================================
    //  PRIVATE HELPERS
    // ================================================================
    private BigDecimal average(List<BigDecimal> values) {
        if (values.isEmpty()) return BigDecimal.ZERO;
        BigDecimal sum = values.stream().reduce(BigDecimal.ZERO, BigDecimal::add);
        return sum.divide(BigDecimal.valueOf(values.size()), 2, RoundingMode.HALF_UP);
    }

    private BigDecimal median(List<BigDecimal> sorted) {
        int size = sorted.size();
        if (size == 0) return BigDecimal.ZERO;
        if (size % 2 == 1) return sorted.get(size / 2);
        BigDecimal lo = sorted.get(size / 2 - 1);
        BigDecimal hi = sorted.get(size / 2);
        return lo.add(hi).divide(BigDecimal.valueOf(2), 2, RoundingMode.HALF_UP);
    }

    public AnalyticsService(final MutualFundRepository fundRepository, final InvestmentRepository investmentRepository, final UserRepository userRepository) {
        this.fundRepository = fundRepository;
        this.investmentRepository = investmentRepository;
        this.userRepository = userRepository;
    }
}
