// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.service;

import com.klu.dto.UserResponseDTO;
import com.klu.entity.User;
import com.klu.repository.UserRepository;
import com.klu.util.MappingUtil;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

/**
 * Service layer for User management.
 *
 * Provides full CRUD operations accessible to the ADMIN role,
 * plus self-lookup by email for any authenticated user.
 */
@Service
public class UserService {
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    // ---- Request DTO ----
    public record UserUpdateRequest(String name, String email, String password, String role) {
    }

    // ================================================================
    //  READ
    // ================================================================
    /**
     * Return all users (Admin-only).
     */
    @Transactional(readOnly = true)
    public List<UserResponseDTO> getAllUsers() {
        return userRepository.findAll().stream().map(MappingUtil::toUserResponse).toList();
    }

    /**
     * Return a single user by primary key.
     */
    @Transactional(readOnly = true)
    public UserResponseDTO getUserById(Long id) {
        User user = findUserOrThrow(id);
        return MappingUtil.toUserResponse(user);
    }

    /**
     * Lookup by email (used for profile / self-view).
     */
    @Transactional(readOnly = true)
    public UserResponseDTO getUserByEmail(String email) {
        User user = userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("User not found with email: " + email));
        return MappingUtil.toUserResponse(user);
    }

    /**
     * Return all users with a given role.
     */
    @Transactional(readOnly = true)
    public List<UserResponseDTO> getUsersByRole(String role) {
        User.Role userRole = User.Role.valueOf(role.toUpperCase());
        return userRepository.findByRole(userRole).stream().map(MappingUtil::toUserResponse).toList();
    }

    // ================================================================
    //  UPDATE
    // ================================================================
    /**
     * Update the role of an existing user (Admin-only).
     */
    @Transactional
    public UserResponseDTO updateRole(Long id, String role) {
        User user = findUserOrThrow(id);
        user.setRole(User.Role.valueOf(role.toUpperCase()));
        return MappingUtil.toUserResponse(userRepository.save(user));
    }

    /**
     * Update name / email / password (partial update – null values are ignored).
     */
    @Transactional
    public UserResponseDTO updateUser(Long id, UserUpdateRequest req) {
        User user = findUserOrThrow(id);
        if (req.name() != null && !req.name().isBlank()) {
            user.setName(req.name());
        }
        if (req.email() != null && !req.email().isBlank()) {
            user.setEmail(req.email());
        }
        if (req.password() != null && !req.password().isBlank()) {
            user.setPassword(passwordEncoder.encode(req.password()));
        }
        if (req.role() != null && !req.role().isBlank()) {
            user.setRole(User.Role.valueOf(req.role().toUpperCase()));
        }
        return MappingUtil.toUserResponse(userRepository.save(user));
    }

    // ================================================================
    //  DELETE (soft)
    // ================================================================
    /**
     * Soft-disable a user account (does not permanently delete).
     */
    @Transactional
    public void deleteUser(Long id) {
        User user = findUserOrThrow(id);
        user.setEnabled(false);
        userRepository.save(user);
    }

    // ================================================================
    //  PRIVATE HELPERS
    // ================================================================
    private User findUserOrThrow(Long id) {
        return userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found with id: " + id));
    }

    public UserService(final UserRepository userRepository, final PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }
}
