// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.entity;

import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.persistence.*;


/**
 * Records a single investment made by a {@link User} into a {@link MutualFund}.
 *
 * ┌─────────────────┬───────────────────────────────────────────────────────┐
 * │  Field          │  Description                                          │
 * ├─────────────────┼───────────────────────────────────────────────────────┤
 * │  id             │  Auto-generated primary key                           │
 * │  userId         │  FK → users.id  (exposed directly in API responses)   │
 * │  fundId         │  FK → mutual_funds.id  (exposed in API responses)     │
 * │  amount         │  Invested amount in INR                               │
 * │  date           │  Calendar date of investment  (maps to investment_date)│
 * │  units          │  Units = amount ÷ NAV  (computed at buy time)         │
 * │  purchaseNav    │  NAV at time of purchase (for gain/loss calc)         │
 * │  type           │  LUMP_SUM | SIP                                       │
 * │  status         │  ACTIVE | REDEEMED | CANCELLED                        │
 * └─────────────────┴───────────────────────────────────────────────────────┘
 */
@Entity
@Table(name = "investments")
public class Investment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // ── Foreign key relationships (JPA) ────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fund_id", nullable = false)
    private MutualFund mutualFund;
    // ── Core investment fields ──────────────────────────────────────
    /**
     * Amount invested in INR (e.g. 10000.00)
     */
    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;
    /**
     * Date of investment.
     * Column name is {@code investment_date} in the DB;
     * exposed as {@code date} in the API layer.
     */
    @Column(name = "investment_date", nullable = false)
    private LocalDate date;
    // ── Derived / computed fields ───────────────────────────────────
    /**
     * Units purchased = amount ÷ purchaseNav (computed at buy time)
     */
    @Column(nullable = false, precision = 15, scale = 4)
    private BigDecimal units;
    /**
     * NAV per unit at the time of investment
     */
    @Column(name = "purchase_nav", nullable = false, precision = 14, scale = 4)
    private BigDecimal purchaseNav;
    // ── Classification ──────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private InvestmentType type;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private InvestmentStatus status;

    // ── Enums ───────────────────────────────────────────────────────
    public enum InvestmentType {
        LUMP_SUM, SIP;
    }


    public enum InvestmentStatus {
        ACTIVE, REDEEMED, CANCELLED;
    }

    private static InvestmentStatus $default$status() {
        return InvestmentStatus.ACTIVE;
    }

    public static class InvestmentBuilder {

        private Long id;

        private User user;

        private MutualFund mutualFund;

        private BigDecimal amount;

        private LocalDate date;

        private BigDecimal units;

        private BigDecimal purchaseNav;

        private InvestmentType type;

        private boolean status$set;

        private InvestmentStatus status$value;

        InvestmentBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder mutualFund(final MutualFund mutualFund) {
            this.mutualFund = mutualFund;
            return this;
        }

        /**
         * Amount invested in INR (e.g. 10000.00)
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Date of investment.
         * Column name is {@code investment_date} in the DB;
         * exposed as {@code date} in the API layer.
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder date(final LocalDate date) {
            this.date = date;
            return this;
        }

        /**
         * Units purchased = amount ÷ purchaseNav (computed at buy time)
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder units(final BigDecimal units) {
            this.units = units;
            return this;
        }

        /**
         * NAV per unit at the time of investment
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder purchaseNav(final BigDecimal purchaseNav) {
            this.purchaseNav = purchaseNav;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder type(final InvestmentType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Investment.InvestmentBuilder status(final InvestmentStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        public Investment build() {
            InvestmentStatus status$value = this.status$value;
            if (!this.status$set) status$value = Investment.$default$status();
            return new Investment(this.id, this.user, this.mutualFund, this.amount, this.date, this.units, this.purchaseNav, this.type, status$value);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "Investment.InvestmentBuilder(id=" + this.id + ", user=" + this.user + ", mutualFund=" + this.mutualFund + ", amount=" + this.amount + ", date=" + this.date + ", units=" + this.units + ", purchaseNav=" + this.purchaseNav + ", type=" + this.type + ", status$value=" + this.status$value + ")";
        }
    }

    public static Investment.InvestmentBuilder builder() {
        return new Investment.InvestmentBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public User getUser() {
        return this.user;
    }

    public MutualFund getMutualFund() {
        return this.mutualFund;
    }

    /**
     * Amount invested in INR (e.g. 10000.00)
     */

    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Date of investment.
     * Column name is {@code investment_date} in the DB;
     * exposed as {@code date} in the API layer.
     */

    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Units purchased = amount ÷ purchaseNav (computed at buy time)
     */

    public BigDecimal getUnits() {
        return this.units;
    }

    /**
     * NAV per unit at the time of investment
     */

    public BigDecimal getPurchaseNav() {
        return this.purchaseNav;
    }

    public InvestmentType getType() {
        return this.type;
    }

    public InvestmentStatus getStatus() {
        return this.status;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setUser(final User user) {
        this.user = user;
    }

    public void setMutualFund(final MutualFund mutualFund) {
        this.mutualFund = mutualFund;
    }

    /**
     * Amount invested in INR (e.g. 10000.00)
     */

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Date of investment.
     * Column name is {@code investment_date} in the DB;
     * exposed as {@code date} in the API layer.
     */

    public void setDate(final LocalDate date) {
        this.date = date;
    }

    /**
     * Units purchased = amount ÷ purchaseNav (computed at buy time)
     */

    public void setUnits(final BigDecimal units) {
        this.units = units;
    }

    /**
     * NAV per unit at the time of investment
     */

    public void setPurchaseNav(final BigDecimal purchaseNav) {
        this.purchaseNav = purchaseNav;
    }

    public void setType(final InvestmentType type) {
        this.type = type;
    }

    public void setStatus(final InvestmentStatus status) {
        this.status = status;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Investment)) return false;
        final Investment other = (Investment) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$mutualFund = this.getMutualFund();
        final java.lang.Object other$mutualFund = other.getMutualFund();
        if (this$mutualFund == null ? other$mutualFund != null : !this$mutualFund.equals(other$mutualFund)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final java.lang.Object this$units = this.getUnits();
        final java.lang.Object other$units = other.getUnits();
        if (this$units == null ? other$units != null : !this$units.equals(other$units)) return false;
        final java.lang.Object this$purchaseNav = this.getPurchaseNav();
        final java.lang.Object other$purchaseNav = other.getPurchaseNav();
        if (this$purchaseNav == null ? other$purchaseNav != null : !this$purchaseNav.equals(other$purchaseNav)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Investment;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $mutualFund = this.getMutualFund();
        result = result * PRIME + ($mutualFund == null ? 43 : $mutualFund.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final java.lang.Object $units = this.getUnits();
        result = result * PRIME + ($units == null ? 43 : $units.hashCode());
        final java.lang.Object $purchaseNav = this.getPurchaseNav();
        result = result * PRIME + ($purchaseNav == null ? 43 : $purchaseNav.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "Investment(id=" + this.getId() + ", user=" + this.getUser() + ", mutualFund=" + this.getMutualFund() + ", amount=" + this.getAmount() + ", date=" + this.getDate() + ", units=" + this.getUnits() + ", purchaseNav=" + this.getPurchaseNav() + ", type=" + this.getType() + ", status=" + this.getStatus() + ")";
    }

    public Investment() {
        this.status = Investment.$default$status();
    }

    /**
     * Creates a new {@code Investment} instance.
     *
     * @param id
     * @param user
     * @param mutualFund
     * @param amount Amount invested in INR (e.g. 10000.00)
     * @param date Date of investment.
     * Column name is {@code investment_date} in the DB;
     * exposed as {@code date} in the API layer.
     * @param units Units purchased = amount ÷ purchaseNav (computed at buy time)
     * @param purchaseNav NAV per unit at the time of investment
     * @param type
     * @param status
     */

    public Investment(final Long id, final User user, final MutualFund mutualFund, final BigDecimal amount, final LocalDate date, final BigDecimal units, final BigDecimal purchaseNav, final InvestmentType type, final InvestmentStatus status) {
        this.id = id;
        this.user = user;
        this.mutualFund = mutualFund;
        this.amount = amount;
        this.date = date;
        this.units = units;
        this.purchaseNav = purchaseNav;
        this.type = type;
        this.status = status;
    }
}
