// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.util.List;

/**
 * Represents a Mutual Fund available on the platform.
 *
 * ┌──────────────┬──────────────────────────────────────────────────┐
 * │   Field      │  Description                                     │
 * ├──────────────┼──────────────────────────────────────────────────┤
 * │ id           │  Auto-generated primary key                      │
 * │ fundName     │  Full name of the fund  (e.g. "Axis Bluechip")   │
 * │ category     │  EQUITY | DEBT | HYBRID | LIQUID                 │
 * │ riskLevel    │  LOW | MODERATE | HIGH | VERY_HIGH               │
 * │ returns      │  Annualised return % (e.g. 12.50)                │
 * │ nav          │  Net Asset Value per unit  (e.g. 45.23)          │
 * │ description  │  Free-text description of the fund               │
 * │ active       │  Soft-delete flag (false = not visible to users)  │
 * └──────────────┴──────────────────────────────────────────────────┘
 */
@Entity
@Table(name = "mutual_funds")
public class MutualFund {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Full name of the mutual fund
     */
    @Column(name = "fund_name", nullable = false, length = 150)
    private String fundName;
    /**
     * Broad classification of the fund.
     * Typical values: EQUITY, DEBT, HYBRID, LIQUID, ELSS, INDEX
     */
    @Column(nullable = false, length = 50)
    private String category;
    /**
     * Risk level of the fund.
     * LOW → safest, VERY_HIGH → most volatile.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false, length = 20)
    private RiskLevel riskLevel;
    /**
     * Annualised return percentage (e.g. 12.50 means 12.50 %).
     * Allows up to 6 integer digits and 2 decimal places.
     */
    @Column(nullable = false, precision = 8, scale = 2)
    private BigDecimal returns;
    /**
     * Net Asset Value — price of one unit of this fund in INR.
     * Allows up to 10 integer digits and 4 decimal places.
     */
    @Column(nullable = false, precision = 14, scale = 4)
    private BigDecimal nav;
    /**
     * Optional free-text description about the fund's strategy,
     * objective, or any other relevant information.
     */
    @Column(columnDefinition = "TEXT")
    private String description;
    /**
     * Soft-delete flag; false = fund is deactivated / hidden from investors.
     */
    @Column(nullable = false)
    private boolean active;
    /**
     * Investments placed in this fund.
     * Loaded lazily to avoid N+1 queries.
     */
    @OneToMany(mappedBy = "mutualFund", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Investment> investments;

    // ── Risk Level Enum ─────────────────────────────────────────────
    public enum RiskLevel {
        LOW, MODERATE, HIGH, VERY_HIGH;
    }

    private static boolean $default$active() {
        return true;
    }

    public static class MutualFundBuilder {

        private Long id;

        private String fundName;

        private String category;

        private RiskLevel riskLevel;

        private BigDecimal returns;

        private BigDecimal nav;

        private String description;

        private boolean active$set;

        private boolean active$value;

        private List<Investment> investments;

        MutualFundBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * Full name of the mutual fund
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * Broad classification of the fund.
         * Typical values: EQUITY, DEBT, HYBRID, LIQUID, ELSS, INDEX
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * Risk level of the fund.
         * LOW → safest, VERY_HIGH → most volatile.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder riskLevel(final RiskLevel riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * Annualised return percentage (e.g. 12.50 means 12.50 %).
         * Allows up to 6 integer digits and 2 decimal places.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder returns(final BigDecimal returns) {
            this.returns = returns;
            return this;
        }

        /**
         * Net Asset Value — price of one unit of this fund in INR.
         * Allows up to 10 integer digits and 4 decimal places.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder nav(final BigDecimal nav) {
            this.nav = nav;
            return this;
        }

        /**
         * Optional free-text description about the fund's strategy,
         * objective, or any other relevant information.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * Soft-delete flag; false = fund is deactivated / hidden from investors.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * Investments placed in this fund.
         * Loaded lazily to avoid N+1 queries.
         * @return {@code this}.
         */

        public MutualFund.MutualFundBuilder investments(final List<Investment> investments) {
            this.investments = investments;
            return this;
        }

        public MutualFund build() {
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = MutualFund.$default$active();
            return new MutualFund(this.id, this.fundName, this.category, this.riskLevel, this.returns, this.nav, this.description, active$value, this.investments);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MutualFund.MutualFundBuilder(id=" + this.id + ", fundName=" + this.fundName + ", category=" + this.category + ", riskLevel=" + this.riskLevel + ", returns=" + this.returns + ", nav=" + this.nav + ", description=" + this.description + ", active$value=" + this.active$value + ", investments=" + this.investments + ")";
        }
    }

    public static MutualFund.MutualFundBuilder builder() {
        return new MutualFund.MutualFundBuilder();
    }

    public Long getId() {
        return this.id;
    }

    /**
     * Full name of the mutual fund
     */

    public String getFundName() {
        return this.fundName;
    }

    /**
     * Broad classification of the fund.
     * Typical values: EQUITY, DEBT, HYBRID, LIQUID, ELSS, INDEX
     */

    public String getCategory() {
        return this.category;
    }

    /**
     * Risk level of the fund.
     * LOW → safest, VERY_HIGH → most volatile.
     */

    public RiskLevel getRiskLevel() {
        return this.riskLevel;
    }

    /**
     * Annualised return percentage (e.g. 12.50 means 12.50 %).
     * Allows up to 6 integer digits and 2 decimal places.
     */

    public BigDecimal getReturns() {
        return this.returns;
    }

    /**
     * Net Asset Value — price of one unit of this fund in INR.
     * Allows up to 10 integer digits and 4 decimal places.
     */

    public BigDecimal getNav() {
        return this.nav;
    }

    /**
     * Optional free-text description about the fund's strategy,
     * objective, or any other relevant information.
     */

    public String getDescription() {
        return this.description;
    }

    /**
     * Soft-delete flag; false = fund is deactivated / hidden from investors.
     */

    public boolean isActive() {
        return this.active;
    }

    /**
     * Investments placed in this fund.
     * Loaded lazily to avoid N+1 queries.
     */

    public List<Investment> getInvestments() {
        return this.investments;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    /**
     * Full name of the mutual fund
     */

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    /**
     * Broad classification of the fund.
     * Typical values: EQUITY, DEBT, HYBRID, LIQUID, ELSS, INDEX
     */

    public void setCategory(final String category) {
        this.category = category;
    }

    /**
     * Risk level of the fund.
     * LOW → safest, VERY_HIGH → most volatile.
     */

    public void setRiskLevel(final RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * Annualised return percentage (e.g. 12.50 means 12.50 %).
     * Allows up to 6 integer digits and 2 decimal places.
     */

    public void setReturns(final BigDecimal returns) {
        this.returns = returns;
    }

    /**
     * Net Asset Value — price of one unit of this fund in INR.
     * Allows up to 10 integer digits and 4 decimal places.
     */

    public void setNav(final BigDecimal nav) {
        this.nav = nav;
    }

    /**
     * Optional free-text description about the fund's strategy,
     * objective, or any other relevant information.
     */

    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Soft-delete flag; false = fund is deactivated / hidden from investors.
     */

    public void setActive(final boolean active) {
        this.active = active;
    }

    /**
     * Investments placed in this fund.
     * Loaded lazily to avoid N+1 queries.
     */

    public void setInvestments(final List<Investment> investments) {
        this.investments = investments;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MutualFund)) return false;
        final MutualFund other = (MutualFund) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isActive() != other.isActive()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$returns = this.getReturns();
        final java.lang.Object other$returns = other.getReturns();
        if (this$returns == null ? other$returns != null : !this$returns.equals(other$returns)) return false;
        final java.lang.Object this$nav = this.getNav();
        final java.lang.Object other$nav = other.getNav();
        if (this$nav == null ? other$nav != null : !this$nav.equals(other$nav)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$investments = this.getInvestments();
        final java.lang.Object other$investments = other.getInvestments();
        if (this$investments == null ? other$investments != null : !this$investments.equals(other$investments)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MutualFund;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isActive() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $returns = this.getReturns();
        result = result * PRIME + ($returns == null ? 43 : $returns.hashCode());
        final java.lang.Object $nav = this.getNav();
        result = result * PRIME + ($nav == null ? 43 : $nav.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $investments = this.getInvestments();
        result = result * PRIME + ($investments == null ? 43 : $investments.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "MutualFund(id=" + this.getId() + ", fundName=" + this.getFundName() + ", category=" + this.getCategory() + ", riskLevel=" + this.getRiskLevel() + ", returns=" + this.getReturns() + ", nav=" + this.getNav() + ", description=" + this.getDescription() + ", active=" + this.isActive() + ", investments=" + this.getInvestments() + ")";
    }

    public MutualFund() {
        this.active = MutualFund.$default$active();
    }

    /**
     * Creates a new {@code MutualFund} instance.
     *
     * @param id
     * @param fundName Full name of the mutual fund
     * @param category Broad classification of the fund.
     * Typical values: EQUITY, DEBT, HYBRID, LIQUID, ELSS, INDEX
     * @param riskLevel Risk level of the fund.
     * LOW → safest, VERY_HIGH → most volatile.
     * @param returns Annualised return percentage (e.g. 12.50 means 12.50 %).
     * Allows up to 6 integer digits and 2 decimal places.
     * @param nav Net Asset Value — price of one unit of this fund in INR.
     * Allows up to 10 integer digits and 4 decimal places.
     * @param description Optional free-text description about the fund's strategy,
     * objective, or any other relevant information.
     * @param active Soft-delete flag; false = fund is deactivated / hidden from investors.
     * @param investments Investments placed in this fund.
     * Loaded lazily to avoid N+1 queries.
     */

    public MutualFund(final Long id, final String fundName, final String category, final RiskLevel riskLevel, final BigDecimal returns, final BigDecimal nav, final String description, final boolean active, final List<Investment> investments) {
        this.id = id;
        this.fundName = fundName;
        this.category = category;
        this.riskLevel = riskLevel;
        this.returns = returns;
        this.nav = nav;
        this.description = description;
        this.active = active;
        this.investments = investments;
    }
}
