// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.entity;

import jakarta.persistence.*;

/**
 * Represents a registered user of the Mutual Fund platform.
 *
 * Fields
 * ------
 * id       – auto-generated primary key
 * name     – full display name of the user
 * email    – unique email address (used for contact / lookup)
 * password – BCrypt-hashed password (never returned to client)
 * role     – one of ADMIN | INVESTOR | ADVISOR | ANALYST
 * enabled  – soft-disable flag (false = account deactivated)
 */
@Entity
@Table(name = "users", uniqueConstraints = {@UniqueConstraint(columnNames = "email")})
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Full display name, e.g. "John Smith"
     */
    @Column(nullable = false, length = 100)
    private String name;
    /**
     * Unique email – used as login username by Spring Security
     */
    @Column(nullable = false, unique = true, length = 100)
    private String email;
    /**
     * BCrypt-hashed password – never expose in responses
     */
    @Column(nullable = false)
    private String password;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;
    @Column(nullable = false)
    private boolean enabled;

    // ---- Role enum ----
    public enum Role {
        ADMIN, INVESTOR, ADVISOR, ANALYST;
    }

    private static boolean $default$enabled() {
        return true;
    }

    public static class UserBuilder {

        private Long id;

        private String name;

        private String email;

        private String password;

        private Role role;

        private boolean enabled$set;

        private boolean enabled$value;

        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * Full display name, e.g. "John Smith"
         * @return {@code this}.
         */

        public User.UserBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * Unique email – used as login username by Spring Security
         * @return {@code this}.
         */

        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * BCrypt-hashed password – never expose in responses
         * @return {@code this}.
         */

        public User.UserBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder role(final Role role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder enabled(final boolean enabled) {
            this.enabled$value = enabled;
            enabled$set = true;
            return this;
        }

        public User build() {
            boolean enabled$value = this.enabled$value;
            if (!this.enabled$set) enabled$value = User.$default$enabled();
            return new User(this.id, this.name, this.email, this.password, this.role, enabled$value);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", password=" + this.password + ", role=" + this.role + ", enabled$value=" + this.enabled$value + ")";
        }
    }

    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    public Long getId() {
        return this.id;
    }

    /**
     * Full display name, e.g. "John Smith"
     */

    public String getName() {
        return this.name;
    }

    /**
     * Unique email – used as login username by Spring Security
     */

    public String getEmail() {
        return this.email;
    }

    /**
     * BCrypt-hashed password – never expose in responses
     */

    public String getPassword() {
        return this.password;
    }

    public Role getRole() {
        return this.role;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    /**
     * Full display name, e.g. "John Smith"
     */

    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Unique email – used as login username by Spring Security
     */

    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * BCrypt-hashed password – never expose in responses
     */

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setRole(final Role role) {
        this.role = role;
    }

    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isEnabled() != other.isEnabled()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isEnabled() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", role=" + this.getRole() + ", enabled=" + this.isEnabled() + ")";
    }

    public User() {
        this.enabled = User.$default$enabled();
    }

    /**
     * Creates a new {@code User} instance.
     *
     * @param id
     * @param name Full display name, e.g. "John Smith"
     * @param email Unique email – used as login username by Spring Security
     * @param password BCrypt-hashed password – never expose in responses
     * @param role
     * @param enabled
     */

    public User(final Long id, final String name, final String email, final String password, final Role role, final boolean enabled) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.enabled = enabled;
    }
}
