// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.dto;

/**
 * Outbound DTO returned after successful authentication (register / login).
 *
 * Frontend usage:
 *   Store {@code token} and send as {@code Authorization: Bearer <token>}
 *   on all subsequent requests.
 */
public class AuthResponseDTO {
    /**
     * Signed JWT string
     */
    private String token;
    /**
     * Always "Bearer"
     */
    private String tokenType;
    /**
     * User's full display name
     */
    private String name;
    /**
     * User's email (also the JWT subject)
     */
    private String email;
    /**
     * Granted role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */
    private String role;
    /**
     * Database primary key of the authenticated user
     */
    private Long userId;

    private static String $default$tokenType() {
        return "Bearer";
    }

    public static class AuthResponseDTOBuilder {

        private String token;

        private boolean tokenType$set;

        private String tokenType$value;

        private String name;

        private String email;

        private String role;

        private Long userId;

        AuthResponseDTOBuilder() {
        }

        /**
         * Signed JWT string
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder token(final String token) {
            this.token = token;
            return this;
        }

        /**
         * Always "Bearer"
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder tokenType(final String tokenType) {
            this.tokenType$value = tokenType;
            tokenType$set = true;
            return this;
        }

        /**
         * User's full display name
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * User's email (also the JWT subject)
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * Granted role: ADMIN | INVESTOR | ADVISOR | ANALYST
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * Database primary key of the authenticated user
         * @return {@code this}.
         */

        public AuthResponseDTO.AuthResponseDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        public AuthResponseDTO build() {
            String tokenType$value = this.tokenType$value;
            if (!this.tokenType$set) tokenType$value = AuthResponseDTO.$default$tokenType();
            return new AuthResponseDTO(this.token, tokenType$value, this.name, this.email, this.role, this.userId);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "AuthResponseDTO.AuthResponseDTOBuilder(token=" + this.token + ", tokenType$value=" + this.tokenType$value + ", name=" + this.name + ", email=" + this.email + ", role=" + this.role + ", userId=" + this.userId + ")";
        }
    }

    public static AuthResponseDTO.AuthResponseDTOBuilder builder() {
        return new AuthResponseDTO.AuthResponseDTOBuilder();
    }

    /**
     * Signed JWT string
     */

    public String getToken() {
        return this.token;
    }

    /**
     * Always "Bearer"
     */

    public String getTokenType() {
        return this.tokenType;
    }

    /**
     * User's full display name
     */

    public String getName() {
        return this.name;
    }

    /**
     * User's email (also the JWT subject)
     */

    public String getEmail() {
        return this.email;
    }

    /**
     * Granted role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */

    public String getRole() {
        return this.role;
    }

    /**
     * Database primary key of the authenticated user
     */

    public Long getUserId() {
        return this.userId;
    }

    /**
     * Signed JWT string
     */

    public void setToken(final String token) {
        this.token = token;
    }

    /**
     * Always "Bearer"
     */

    public void setTokenType(final String tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * User's full display name
     */

    public void setName(final String name) {
        this.name = name;
    }

    /**
     * User's email (also the JWT subject)
     */

    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * Granted role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */

    public void setRole(final String role) {
        this.role = role;
    }

    /**
     * Database primary key of the authenticated user
     */

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponseDTO)) return false;
        final AuthResponseDTO other = (AuthResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$tokenType = this.getTokenType();
        final java.lang.Object other$tokenType = other.getTokenType();
        if (this$tokenType == null ? other$tokenType != null : !this$tokenType.equals(other$tokenType)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponseDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $tokenType = this.getTokenType();
        result = result * PRIME + ($tokenType == null ? 43 : $tokenType.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "AuthResponseDTO(token=" + this.getToken() + ", tokenType=" + this.getTokenType() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", role=" + this.getRole() + ", userId=" + this.getUserId() + ")";
    }

    public AuthResponseDTO() {
        this.tokenType = AuthResponseDTO.$default$tokenType();
    }

    /**
     * Creates a new {@code AuthResponseDTO} instance.
     *
     * @param token Signed JWT string
     * @param tokenType Always "Bearer"
     * @param name User's full display name
     * @param email User's email (also the JWT subject)
     * @param role Granted role: ADMIN | INVESTOR | ADVISOR | ANALYST
     * @param userId Database primary key of the authenticated user
     */

    public AuthResponseDTO(final String token, final String tokenType, final String name, final String email, final String role, final Long userId) {
        this.token = token;
        this.tokenType = tokenType;
        this.name = name;
        this.email = email;
        this.role = role;
        this.userId = userId;
    }
}
