// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Outbound DTO for dashboard / portfolio summary statistics.
 */
public class DashboardStatsDTO {
    private BigDecimal totalInvested; // Sum of all active investment amounts
    private BigDecimal currentValue; // Sum of (units × currentNav) for all active
    private BigDecimal gainLoss; // currentValue − totalInvested
    private BigDecimal gainLossPercent; // (gainLoss / totalInvested) × 100
    private Long activeFundsCount; // Distinct funds with ACTIVE investments
    private Long totalInvestmentsCount; // Total number of investment records

    public static class DashboardStatsDTOBuilder {

        private BigDecimal totalInvested;

        private BigDecimal currentValue;

        private BigDecimal gainLoss;

        private BigDecimal gainLossPercent;

        private Long activeFundsCount;

        private Long totalInvestmentsCount;

        DashboardStatsDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder totalInvested(final BigDecimal totalInvested) {
            this.totalInvested = totalInvested;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder currentValue(final BigDecimal currentValue) {
            this.currentValue = currentValue;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder gainLoss(final BigDecimal gainLoss) {
            this.gainLoss = gainLoss;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder gainLossPercent(final BigDecimal gainLossPercent) {
            this.gainLossPercent = gainLossPercent;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder activeFundsCount(final Long activeFundsCount) {
            this.activeFundsCount = activeFundsCount;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DashboardStatsDTO.DashboardStatsDTOBuilder totalInvestmentsCount(final Long totalInvestmentsCount) {
            this.totalInvestmentsCount = totalInvestmentsCount;
            return this;
        }

        public DashboardStatsDTO build() {
            return new DashboardStatsDTO(this.totalInvested, this.currentValue, this.gainLoss, this.gainLossPercent, this.activeFundsCount, this.totalInvestmentsCount);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "DashboardStatsDTO.DashboardStatsDTOBuilder(totalInvested=" + this.totalInvested + ", currentValue=" + this.currentValue + ", gainLoss=" + this.gainLoss + ", gainLossPercent=" + this.gainLossPercent + ", activeFundsCount=" + this.activeFundsCount + ", totalInvestmentsCount=" + this.totalInvestmentsCount + ")";
        }
    }

    public static DashboardStatsDTO.DashboardStatsDTOBuilder builder() {
        return new DashboardStatsDTO.DashboardStatsDTOBuilder();
    }

    public BigDecimal getTotalInvested() {
        return this.totalInvested;
    }

    public BigDecimal getCurrentValue() {
        return this.currentValue;
    }

    public BigDecimal getGainLoss() {
        return this.gainLoss;
    }

    public BigDecimal getGainLossPercent() {
        return this.gainLossPercent;
    }

    public Long getActiveFundsCount() {
        return this.activeFundsCount;
    }

    public Long getTotalInvestmentsCount() {
        return this.totalInvestmentsCount;
    }

    public void setTotalInvested(final BigDecimal totalInvested) {
        this.totalInvested = totalInvested;
    }

    public void setCurrentValue(final BigDecimal currentValue) {
        this.currentValue = currentValue;
    }

    public void setGainLoss(final BigDecimal gainLoss) {
        this.gainLoss = gainLoss;
    }

    public void setGainLossPercent(final BigDecimal gainLossPercent) {
        this.gainLossPercent = gainLossPercent;
    }

    public void setActiveFundsCount(final Long activeFundsCount) {
        this.activeFundsCount = activeFundsCount;
    }

    public void setTotalInvestmentsCount(final Long totalInvestmentsCount) {
        this.totalInvestmentsCount = totalInvestmentsCount;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardStatsDTO)) return false;
        final DashboardStatsDTO other = (DashboardStatsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$activeFundsCount = this.getActiveFundsCount();
        final java.lang.Object other$activeFundsCount = other.getActiveFundsCount();
        if (this$activeFundsCount == null ? other$activeFundsCount != null : !this$activeFundsCount.equals(other$activeFundsCount)) return false;
        final java.lang.Object this$totalInvestmentsCount = this.getTotalInvestmentsCount();
        final java.lang.Object other$totalInvestmentsCount = other.getTotalInvestmentsCount();
        if (this$totalInvestmentsCount == null ? other$totalInvestmentsCount != null : !this$totalInvestmentsCount.equals(other$totalInvestmentsCount)) return false;
        final java.lang.Object this$totalInvested = this.getTotalInvested();
        final java.lang.Object other$totalInvested = other.getTotalInvested();
        if (this$totalInvested == null ? other$totalInvested != null : !this$totalInvested.equals(other$totalInvested)) return false;
        final java.lang.Object this$currentValue = this.getCurrentValue();
        final java.lang.Object other$currentValue = other.getCurrentValue();
        if (this$currentValue == null ? other$currentValue != null : !this$currentValue.equals(other$currentValue)) return false;
        final java.lang.Object this$gainLoss = this.getGainLoss();
        final java.lang.Object other$gainLoss = other.getGainLoss();
        if (this$gainLoss == null ? other$gainLoss != null : !this$gainLoss.equals(other$gainLoss)) return false;
        final java.lang.Object this$gainLossPercent = this.getGainLossPercent();
        final java.lang.Object other$gainLossPercent = other.getGainLossPercent();
        if (this$gainLossPercent == null ? other$gainLossPercent != null : !this$gainLossPercent.equals(other$gainLossPercent)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardStatsDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $activeFundsCount = this.getActiveFundsCount();
        result = result * PRIME + ($activeFundsCount == null ? 43 : $activeFundsCount.hashCode());
        final java.lang.Object $totalInvestmentsCount = this.getTotalInvestmentsCount();
        result = result * PRIME + ($totalInvestmentsCount == null ? 43 : $totalInvestmentsCount.hashCode());
        final java.lang.Object $totalInvested = this.getTotalInvested();
        result = result * PRIME + ($totalInvested == null ? 43 : $totalInvested.hashCode());
        final java.lang.Object $currentValue = this.getCurrentValue();
        result = result * PRIME + ($currentValue == null ? 43 : $currentValue.hashCode());
        final java.lang.Object $gainLoss = this.getGainLoss();
        result = result * PRIME + ($gainLoss == null ? 43 : $gainLoss.hashCode());
        final java.lang.Object $gainLossPercent = this.getGainLossPercent();
        result = result * PRIME + ($gainLossPercent == null ? 43 : $gainLossPercent.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "DashboardStatsDTO(totalInvested=" + this.getTotalInvested() + ", currentValue=" + this.getCurrentValue() + ", gainLoss=" + this.getGainLoss() + ", gainLossPercent=" + this.getGainLossPercent() + ", activeFundsCount=" + this.getActiveFundsCount() + ", totalInvestmentsCount=" + this.getTotalInvestmentsCount() + ")";
    }

    public DashboardStatsDTO() {
    }

    public DashboardStatsDTO(final BigDecimal totalInvested, final BigDecimal currentValue, final BigDecimal gainLoss, final BigDecimal gainLossPercent, final Long activeFundsCount, final Long totalInvestmentsCount) {
        this.totalInvested = totalInvested;
        this.currentValue = currentValue;
        this.gainLoss = gainLoss;
        this.gainLossPercent = gainLossPercent;
        this.activeFundsCount = activeFundsCount;
        this.totalInvestmentsCount = totalInvestmentsCount;
    }
}
