// Generated by delombok at Tue Apr 07 22:43:39 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Inbound DTO for placing an investment.
 *
 * Request body example:
 * <pre>
 * {
 *   "userId": 1,
 *   "fundId": 3,
 *   "amount": 10000.00,
 *   "type":   "LUMP_SUM"
 * }
 * </pre>
 *
 * {@code type} is optional — defaults to {@code LUMP_SUM} if omitted.
 */
public class InvestmentRequestDTO {
    /**
     * ID of the investor (User.id)
     */
    private Long userId;
    /**
     * ID of the fund being invested in (MutualFund.id)
     */
    private Long fundId;
    /**
     * Amount to invest in INR (e.g. 10000.00)
     */
    private BigDecimal amount;
    /**
     * Investment type: LUMP_SUM | SIP  (defaults to LUMP_SUM)
     */
    private String type;

    public static class InvestmentRequestDTOBuilder {

        private Long userId;

        private Long fundId;

        private BigDecimal amount;

        private String type;

        InvestmentRequestDTOBuilder() {
        }

        /**
         * ID of the investor (User.id)
         * @return {@code this}.
         */

        public InvestmentRequestDTO.InvestmentRequestDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * ID of the fund being invested in (MutualFund.id)
         * @return {@code this}.
         */

        public InvestmentRequestDTO.InvestmentRequestDTOBuilder fundId(final Long fundId) {
            this.fundId = fundId;
            return this;
        }

        /**
         * Amount to invest in INR (e.g. 10000.00)
         * @return {@code this}.
         */

        public InvestmentRequestDTO.InvestmentRequestDTOBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Investment type: LUMP_SUM | SIP  (defaults to LUMP_SUM)
         * @return {@code this}.
         */

        public InvestmentRequestDTO.InvestmentRequestDTOBuilder type(final String type) {
            this.type = type;
            return this;
        }

        public InvestmentRequestDTO build() {
            return new InvestmentRequestDTO(this.userId, this.fundId, this.amount, this.type);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "InvestmentRequestDTO.InvestmentRequestDTOBuilder(userId=" + this.userId + ", fundId=" + this.fundId + ", amount=" + this.amount + ", type=" + this.type + ")";
        }
    }

    public static InvestmentRequestDTO.InvestmentRequestDTOBuilder builder() {
        return new InvestmentRequestDTO.InvestmentRequestDTOBuilder();
    }

    /**
     * ID of the investor (User.id)
     */

    public Long getUserId() {
        return this.userId;
    }

    /**
     * ID of the fund being invested in (MutualFund.id)
     */

    public Long getFundId() {
        return this.fundId;
    }

    /**
     * Amount to invest in INR (e.g. 10000.00)
     */

    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Investment type: LUMP_SUM | SIP  (defaults to LUMP_SUM)
     */

    public String getType() {
        return this.type;
    }

    /**
     * ID of the investor (User.id)
     */

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    /**
     * ID of the fund being invested in (MutualFund.id)
     */

    public void setFundId(final Long fundId) {
        this.fundId = fundId;
    }

    /**
     * Amount to invest in INR (e.g. 10000.00)
     */

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Investment type: LUMP_SUM | SIP  (defaults to LUMP_SUM)
     */

    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InvestmentRequestDTO)) return false;
        final InvestmentRequestDTO other = (InvestmentRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$fundId = this.getFundId();
        final java.lang.Object other$fundId = other.getFundId();
        if (this$fundId == null ? other$fundId != null : !this$fundId.equals(other$fundId)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InvestmentRequestDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $fundId = this.getFundId();
        result = result * PRIME + ($fundId == null ? 43 : $fundId.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "InvestmentRequestDTO(userId=" + this.getUserId() + ", fundId=" + this.getFundId() + ", amount=" + this.getAmount() + ", type=" + this.getType() + ")";
    }

    public InvestmentRequestDTO() {
    }

    /**
     * Creates a new {@code InvestmentRequestDTO} instance.
     *
     * @param userId ID of the investor (User.id)
     * @param fundId ID of the fund being invested in (MutualFund.id)
     * @param amount Amount to invest in INR (e.g. 10000.00)
     * @param type Investment type: LUMP_SUM | SIP  (defaults to LUMP_SUM)
     */

    public InvestmentRequestDTO(final Long userId, final Long fundId, final BigDecimal amount, final String type) {
        this.userId = userId;
        this.fundId = fundId;
        this.amount = amount;
        this.type = type;
    }
}
