// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Outbound DTO representing a single Investment record.
 *
 * Exposes userId and fundId directly (as requested),
 * plus computed fields (currentValue, gainLoss) for dashboard use.
 */
public class InvestmentResponseDTO {
    /**
     * Investment primary key
     */
    private Long id;
    /**
     * ID of the investor
     */
    private Long userId;
    /**
     * Display name of the investor
     */
    private String userName;
    /**
     * ID of the fund
     */
    private Long fundId;
    /**
     * Name of the fund
     */
    private String fundName;
    /**
     * Amount invested in INR
     */
    private BigDecimal amount;
    /**
     * Units allocated at time of purchase
     */
    private BigDecimal units;
    /**
     * NAV per unit at time of purchase
     */
    private BigDecimal purchaseNav;
    /**
     * Date of investment
     */
    private LocalDate date;
    /**
     * LUMP_SUM | SIP
     */
    private String type;
    /**
     * ACTIVE | REDEEMED | CANCELLED
     */
    private String status;
    /**
     * units × currentNav  (computed at query time)
     */
    private BigDecimal currentValue;
    /**
     * currentValue − amount
     */
    private BigDecimal gainLoss;
    /**
     * (gainLoss / amount) × 100
     */
    private BigDecimal gainLossPercent;

    public static class InvestmentResponseDTOBuilder {

        private Long id;

        private Long userId;

        private String userName;

        private Long fundId;

        private String fundName;

        private BigDecimal amount;

        private BigDecimal units;

        private BigDecimal purchaseNav;

        private LocalDate date;

        private String type;

        private String status;

        private BigDecimal currentValue;

        private BigDecimal gainLoss;

        private BigDecimal gainLossPercent;

        InvestmentResponseDTOBuilder() {
        }

        /**
         * Investment primary key
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * ID of the investor
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Display name of the investor
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * ID of the fund
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder fundId(final Long fundId) {
            this.fundId = fundId;
            return this;
        }

        /**
         * Name of the fund
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * Amount invested in INR
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Units allocated at time of purchase
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder units(final BigDecimal units) {
            this.units = units;
            return this;
        }

        /**
         * NAV per unit at time of purchase
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder purchaseNav(final BigDecimal purchaseNav) {
            this.purchaseNav = purchaseNav;
            return this;
        }

        /**
         * Date of investment
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder date(final LocalDate date) {
            this.date = date;
            return this;
        }

        /**
         * LUMP_SUM | SIP
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder type(final String type) {
            this.type = type;
            return this;
        }

        /**
         * ACTIVE | REDEEMED | CANCELLED
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * units × currentNav  (computed at query time)
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder currentValue(final BigDecimal currentValue) {
            this.currentValue = currentValue;
            return this;
        }

        /**
         * currentValue − amount
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder gainLoss(final BigDecimal gainLoss) {
            this.gainLoss = gainLoss;
            return this;
        }

        /**
         * (gainLoss / amount) × 100
         * @return {@code this}.
         */

        public InvestmentResponseDTO.InvestmentResponseDTOBuilder gainLossPercent(final BigDecimal gainLossPercent) {
            this.gainLossPercent = gainLossPercent;
            return this;
        }

        public InvestmentResponseDTO build() {
            return new InvestmentResponseDTO(this.id, this.userId, this.userName, this.fundId, this.fundName, this.amount, this.units, this.purchaseNav, this.date, this.type, this.status, this.currentValue, this.gainLoss, this.gainLossPercent);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "InvestmentResponseDTO.InvestmentResponseDTOBuilder(id=" + this.id + ", userId=" + this.userId + ", userName=" + this.userName + ", fundId=" + this.fundId + ", fundName=" + this.fundName + ", amount=" + this.amount + ", units=" + this.units + ", purchaseNav=" + this.purchaseNav + ", date=" + this.date + ", type=" + this.type + ", status=" + this.status + ", currentValue=" + this.currentValue + ", gainLoss=" + this.gainLoss + ", gainLossPercent=" + this.gainLossPercent + ")";
        }
    }

    public static InvestmentResponseDTO.InvestmentResponseDTOBuilder builder() {
        return new InvestmentResponseDTO.InvestmentResponseDTOBuilder();
    }

    /**
     * Investment primary key
     */

    public Long getId() {
        return this.id;
    }

    /**
     * ID of the investor
     */

    public Long getUserId() {
        return this.userId;
    }

    /**
     * Display name of the investor
     */

    public String getUserName() {
        return this.userName;
    }

    /**
     * ID of the fund
     */

    public Long getFundId() {
        return this.fundId;
    }

    /**
     * Name of the fund
     */

    public String getFundName() {
        return this.fundName;
    }

    /**
     * Amount invested in INR
     */

    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Units allocated at time of purchase
     */

    public BigDecimal getUnits() {
        return this.units;
    }

    /**
     * NAV per unit at time of purchase
     */

    public BigDecimal getPurchaseNav() {
        return this.purchaseNav;
    }

    /**
     * Date of investment
     */

    public LocalDate getDate() {
        return this.date;
    }

    /**
     * LUMP_SUM | SIP
     */

    public String getType() {
        return this.type;
    }

    /**
     * ACTIVE | REDEEMED | CANCELLED
     */

    public String getStatus() {
        return this.status;
    }

    /**
     * units × currentNav  (computed at query time)
     */

    public BigDecimal getCurrentValue() {
        return this.currentValue;
    }

    /**
     * currentValue − amount
     */

    public BigDecimal getGainLoss() {
        return this.gainLoss;
    }

    /**
     * (gainLoss / amount) × 100
     */

    public BigDecimal getGainLossPercent() {
        return this.gainLossPercent;
    }

    /**
     * Investment primary key
     */

    public void setId(final Long id) {
        this.id = id;
    }

    /**
     * ID of the investor
     */

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    /**
     * Display name of the investor
     */

    public void setUserName(final String userName) {
        this.userName = userName;
    }

    /**
     * ID of the fund
     */

    public void setFundId(final Long fundId) {
        this.fundId = fundId;
    }

    /**
     * Name of the fund
     */

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    /**
     * Amount invested in INR
     */

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Units allocated at time of purchase
     */

    public void setUnits(final BigDecimal units) {
        this.units = units;
    }

    /**
     * NAV per unit at time of purchase
     */

    public void setPurchaseNav(final BigDecimal purchaseNav) {
        this.purchaseNav = purchaseNav;
    }

    /**
     * Date of investment
     */

    public void setDate(final LocalDate date) {
        this.date = date;
    }

    /**
     * LUMP_SUM | SIP
     */

    public void setType(final String type) {
        this.type = type;
    }

    /**
     * ACTIVE | REDEEMED | CANCELLED
     */

    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * units × currentNav  (computed at query time)
     */

    public void setCurrentValue(final BigDecimal currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * currentValue − amount
     */

    public void setGainLoss(final BigDecimal gainLoss) {
        this.gainLoss = gainLoss;
    }

    /**
     * (gainLoss / amount) × 100
     */

    public void setGainLossPercent(final BigDecimal gainLossPercent) {
        this.gainLossPercent = gainLossPercent;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InvestmentResponseDTO)) return false;
        final InvestmentResponseDTO other = (InvestmentResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$fundId = this.getFundId();
        final java.lang.Object other$fundId = other.getFundId();
        if (this$fundId == null ? other$fundId != null : !this$fundId.equals(other$fundId)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$units = this.getUnits();
        final java.lang.Object other$units = other.getUnits();
        if (this$units == null ? other$units != null : !this$units.equals(other$units)) return false;
        final java.lang.Object this$purchaseNav = this.getPurchaseNav();
        final java.lang.Object other$purchaseNav = other.getPurchaseNav();
        if (this$purchaseNav == null ? other$purchaseNav != null : !this$purchaseNav.equals(other$purchaseNav)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$currentValue = this.getCurrentValue();
        final java.lang.Object other$currentValue = other.getCurrentValue();
        if (this$currentValue == null ? other$currentValue != null : !this$currentValue.equals(other$currentValue)) return false;
        final java.lang.Object this$gainLoss = this.getGainLoss();
        final java.lang.Object other$gainLoss = other.getGainLoss();
        if (this$gainLoss == null ? other$gainLoss != null : !this$gainLoss.equals(other$gainLoss)) return false;
        final java.lang.Object this$gainLossPercent = this.getGainLossPercent();
        final java.lang.Object other$gainLossPercent = other.getGainLossPercent();
        if (this$gainLossPercent == null ? other$gainLossPercent != null : !this$gainLossPercent.equals(other$gainLossPercent)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InvestmentResponseDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $fundId = this.getFundId();
        result = result * PRIME + ($fundId == null ? 43 : $fundId.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $units = this.getUnits();
        result = result * PRIME + ($units == null ? 43 : $units.hashCode());
        final java.lang.Object $purchaseNav = this.getPurchaseNav();
        result = result * PRIME + ($purchaseNav == null ? 43 : $purchaseNav.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $currentValue = this.getCurrentValue();
        result = result * PRIME + ($currentValue == null ? 43 : $currentValue.hashCode());
        final java.lang.Object $gainLoss = this.getGainLoss();
        result = result * PRIME + ($gainLoss == null ? 43 : $gainLoss.hashCode());
        final java.lang.Object $gainLossPercent = this.getGainLossPercent();
        result = result * PRIME + ($gainLossPercent == null ? 43 : $gainLossPercent.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "InvestmentResponseDTO(id=" + this.getId() + ", userId=" + this.getUserId() + ", userName=" + this.getUserName() + ", fundId=" + this.getFundId() + ", fundName=" + this.getFundName() + ", amount=" + this.getAmount() + ", units=" + this.getUnits() + ", purchaseNav=" + this.getPurchaseNav() + ", date=" + this.getDate() + ", type=" + this.getType() + ", status=" + this.getStatus() + ", currentValue=" + this.getCurrentValue() + ", gainLoss=" + this.getGainLoss() + ", gainLossPercent=" + this.getGainLossPercent() + ")";
    }

    public InvestmentResponseDTO() {
    }

    /**
     * Creates a new {@code InvestmentResponseDTO} instance.
     *
     * @param id Investment primary key
     * @param userId ID of the investor
     * @param userName Display name of the investor
     * @param fundId ID of the fund
     * @param fundName Name of the fund
     * @param amount Amount invested in INR
     * @param units Units allocated at time of purchase
     * @param purchaseNav NAV per unit at time of purchase
     * @param date Date of investment
     * @param type LUMP_SUM | SIP
     * @param status ACTIVE | REDEEMED | CANCELLED
     * @param currentValue units × currentNav  (computed at query time)
     * @param gainLoss currentValue − amount
     * @param gainLossPercent (gainLoss / amount) × 100
     */

    public InvestmentResponseDTO(final Long id, final Long userId, final String userName, final Long fundId, final String fundName, final BigDecimal amount, final BigDecimal units, final BigDecimal purchaseNav, final LocalDate date, final String type, final String status, final BigDecimal currentValue, final BigDecimal gainLoss, final BigDecimal gainLossPercent) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.fundId = fundId;
        this.fundName = fundName;
        this.amount = amount;
        this.units = units;
        this.purchaseNav = purchaseNav;
        this.date = date;
        this.type = type;
        this.status = status;
        this.currentValue = currentValue;
        this.gainLoss = gainLoss;
        this.gainLossPercent = gainLossPercent;
    }
}
