// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

/**
 * Inbound DTO for login requests.
 * Credentials: email + password.
 */
public class LoginRequestDTO {
    /**
     * Registered email address
     */
    private String email;
    /**
     * Plain-text password
     */
    private String password;

    public static class LoginRequestDTOBuilder {

        private String email;

        private String password;

        LoginRequestDTOBuilder() {
        }

        /**
         * Registered email address
         * @return {@code this}.
         */

        public LoginRequestDTO.LoginRequestDTOBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * Plain-text password
         * @return {@code this}.
         */

        public LoginRequestDTO.LoginRequestDTOBuilder password(final String password) {
            this.password = password;
            return this;
        }

        public LoginRequestDTO build() {
            return new LoginRequestDTO(this.email, this.password);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "LoginRequestDTO.LoginRequestDTOBuilder(email=" + this.email + ", password=" + this.password + ")";
        }
    }

    public static LoginRequestDTO.LoginRequestDTOBuilder builder() {
        return new LoginRequestDTO.LoginRequestDTOBuilder();
    }

    /**
     * Registered email address
     */

    public String getEmail() {
        return this.email;
    }

    /**
     * Plain-text password
     */

    public String getPassword() {
        return this.password;
    }

    /**
     * Registered email address
     */

    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * Plain-text password
     */

    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LoginRequestDTO)) return false;
        final LoginRequestDTO other = (LoginRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LoginRequestDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "LoginRequestDTO(email=" + this.getEmail() + ", password=" + this.getPassword() + ")";
    }

    public LoginRequestDTO() {
    }

    /**
     * Creates a new {@code LoginRequestDTO} instance.
     *
     * @param email Registered email address
     * @param password Plain-text password
     */

    public LoginRequestDTO(final String email, final String password) {
        this.email = email;
        this.password = password;
    }
}
