// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;
import java.util.List;

/**
 * Monthly investment report for a user or the entire platform.
 *
 * Contains one entry per month, with breakdown by fund category.
 */
public class MonthlyReportDTO {
    private int year;
    private String reportScope; // "USER:{userId}" or "PLATFORM"
    /**
     * One entry per month that has data
     */
    private List<MonthEntry> months;
    /**
     * Summary totals across the entire report period
     */
    private BigDecimal totalInvestedInPeriod;
    private long totalTransactionsInPeriod;
    private long activeFundsInPeriod;


    public static class MonthEntry {
        private int month; // 1–12
        private String monthName; // "January", "February", ...
        private BigDecimal totalInvested; // Sum of amounts in this month
        private long transactionCount;
        private BigDecimal averageAmount; // totalInvested / transactionCount
        private BigDecimal cumulativeTotal; // Running total from Jan through this month
        /**
         * Breakdown by fund category within this month
         */
        private List<CategoryBreakdown> categoryBreakdown;

        public static class MonthEntryBuilder {

            private int month;

            private String monthName;

            private BigDecimal totalInvested;

            private long transactionCount;

            private BigDecimal averageAmount;

            private BigDecimal cumulativeTotal;

            private List<CategoryBreakdown> categoryBreakdown;

            MonthEntryBuilder() {
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder month(final int month) {
                this.month = month;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder monthName(final String monthName) {
                this.monthName = monthName;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder totalInvested(final BigDecimal totalInvested) {
                this.totalInvested = totalInvested;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder transactionCount(final long transactionCount) {
                this.transactionCount = transactionCount;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder averageAmount(final BigDecimal averageAmount) {
                this.averageAmount = averageAmount;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder cumulativeTotal(final BigDecimal cumulativeTotal) {
                this.cumulativeTotal = cumulativeTotal;
                return this;
            }

            /**
             * Breakdown by fund category within this month
             * @return {@code this}.
             */

            public MonthlyReportDTO.MonthEntry.MonthEntryBuilder categoryBreakdown(final List<CategoryBreakdown> categoryBreakdown) {
                this.categoryBreakdown = categoryBreakdown;
                return this;
            }

            public MonthlyReportDTO.MonthEntry build() {
                return new MonthlyReportDTO.MonthEntry(this.month, this.monthName, this.totalInvested, this.transactionCount, this.averageAmount, this.cumulativeTotal, this.categoryBreakdown);
            }

            @java.lang.Override

            public java.lang.String toString() {
                return "MonthlyReportDTO.MonthEntry.MonthEntryBuilder(month=" + this.month + ", monthName=" + this.monthName + ", totalInvested=" + this.totalInvested + ", transactionCount=" + this.transactionCount + ", averageAmount=" + this.averageAmount + ", cumulativeTotal=" + this.cumulativeTotal + ", categoryBreakdown=" + this.categoryBreakdown + ")";
            }
        }

        public static MonthlyReportDTO.MonthEntry.MonthEntryBuilder builder() {
            return new MonthlyReportDTO.MonthEntry.MonthEntryBuilder();
        }

        public int getMonth() {
            return this.month;
        }

        public String getMonthName() {
            return this.monthName;
        }

        public BigDecimal getTotalInvested() {
            return this.totalInvested;
        }

        public long getTransactionCount() {
            return this.transactionCount;
        }

        public BigDecimal getAverageAmount() {
            return this.averageAmount;
        }

        public BigDecimal getCumulativeTotal() {
            return this.cumulativeTotal;
        }

        /**
         * Breakdown by fund category within this month
         */

        public List<CategoryBreakdown> getCategoryBreakdown() {
            return this.categoryBreakdown;
        }

        public void setMonth(final int month) {
            this.month = month;
        }

        public void setMonthName(final String monthName) {
            this.monthName = monthName;
        }

        public void setTotalInvested(final BigDecimal totalInvested) {
            this.totalInvested = totalInvested;
        }

        public void setTransactionCount(final long transactionCount) {
            this.transactionCount = transactionCount;
        }

        public void setAverageAmount(final BigDecimal averageAmount) {
            this.averageAmount = averageAmount;
        }

        public void setCumulativeTotal(final BigDecimal cumulativeTotal) {
            this.cumulativeTotal = cumulativeTotal;
        }

        /**
         * Breakdown by fund category within this month
         */

        public void setCategoryBreakdown(final List<CategoryBreakdown> categoryBreakdown) {
            this.categoryBreakdown = categoryBreakdown;
        }

        @java.lang.Override

        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof MonthlyReportDTO.MonthEntry)) return false;
            final MonthlyReportDTO.MonthEntry other = (MonthlyReportDTO.MonthEntry) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getMonth() != other.getMonth()) return false;
            if (this.getTransactionCount() != other.getTransactionCount()) return false;
            final java.lang.Object this$monthName = this.getMonthName();
            final java.lang.Object other$monthName = other.getMonthName();
            if (this$monthName == null ? other$monthName != null : !this$monthName.equals(other$monthName)) return false;
            final java.lang.Object this$totalInvested = this.getTotalInvested();
            final java.lang.Object other$totalInvested = other.getTotalInvested();
            if (this$totalInvested == null ? other$totalInvested != null : !this$totalInvested.equals(other$totalInvested)) return false;
            final java.lang.Object this$averageAmount = this.getAverageAmount();
            final java.lang.Object other$averageAmount = other.getAverageAmount();
            if (this$averageAmount == null ? other$averageAmount != null : !this$averageAmount.equals(other$averageAmount)) return false;
            final java.lang.Object this$cumulativeTotal = this.getCumulativeTotal();
            final java.lang.Object other$cumulativeTotal = other.getCumulativeTotal();
            if (this$cumulativeTotal == null ? other$cumulativeTotal != null : !this$cumulativeTotal.equals(other$cumulativeTotal)) return false;
            final java.lang.Object this$categoryBreakdown = this.getCategoryBreakdown();
            final java.lang.Object other$categoryBreakdown = other.getCategoryBreakdown();
            if (this$categoryBreakdown == null ? other$categoryBreakdown != null : !this$categoryBreakdown.equals(other$categoryBreakdown)) return false;
            return true;
        }

        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof MonthlyReportDTO.MonthEntry;
        }

        @java.lang.Override

        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getMonth();
            final long $transactionCount = this.getTransactionCount();
            result = result * PRIME + (int) ($transactionCount >>> 32 ^ $transactionCount);
            final java.lang.Object $monthName = this.getMonthName();
            result = result * PRIME + ($monthName == null ? 43 : $monthName.hashCode());
            final java.lang.Object $totalInvested = this.getTotalInvested();
            result = result * PRIME + ($totalInvested == null ? 43 : $totalInvested.hashCode());
            final java.lang.Object $averageAmount = this.getAverageAmount();
            result = result * PRIME + ($averageAmount == null ? 43 : $averageAmount.hashCode());
            final java.lang.Object $cumulativeTotal = this.getCumulativeTotal();
            result = result * PRIME + ($cumulativeTotal == null ? 43 : $cumulativeTotal.hashCode());
            final java.lang.Object $categoryBreakdown = this.getCategoryBreakdown();
            result = result * PRIME + ($categoryBreakdown == null ? 43 : $categoryBreakdown.hashCode());
            return result;
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MonthlyReportDTO.MonthEntry(month=" + this.getMonth() + ", monthName=" + this.getMonthName() + ", totalInvested=" + this.getTotalInvested() + ", transactionCount=" + this.getTransactionCount() + ", averageAmount=" + this.getAverageAmount() + ", cumulativeTotal=" + this.getCumulativeTotal() + ", categoryBreakdown=" + this.getCategoryBreakdown() + ")";
        }

        public MonthEntry() {
        }

        /**
         * Creates a new {@code MonthEntry} instance.
         *
         * @param month
         * @param monthName
         * @param totalInvested
         * @param transactionCount
         * @param averageAmount
         * @param cumulativeTotal
         * @param categoryBreakdown Breakdown by fund category within this month
         */

        public MonthEntry(final int month, final String monthName, final BigDecimal totalInvested, final long transactionCount, final BigDecimal averageAmount, final BigDecimal cumulativeTotal, final List<CategoryBreakdown> categoryBreakdown) {
            this.month = month;
            this.monthName = monthName;
            this.totalInvested = totalInvested;
            this.transactionCount = transactionCount;
            this.averageAmount = averageAmount;
            this.cumulativeTotal = cumulativeTotal;
            this.categoryBreakdown = categoryBreakdown;
        }
    }


    public static class CategoryBreakdown {
        private String category;
        private BigDecimal amount;
        private long transactions;

        public static class CategoryBreakdownBuilder {

            private String category;

            private BigDecimal amount;

            private long transactions;

            CategoryBreakdownBuilder() {
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder category(final String category) {
                this.category = category;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder amount(final BigDecimal amount) {
                this.amount = amount;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder transactions(final long transactions) {
                this.transactions = transactions;
                return this;
            }

            public MonthlyReportDTO.CategoryBreakdown build() {
                return new MonthlyReportDTO.CategoryBreakdown(this.category, this.amount, this.transactions);
            }

            @java.lang.Override

            public java.lang.String toString() {
                return "MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder(category=" + this.category + ", amount=" + this.amount + ", transactions=" + this.transactions + ")";
            }
        }

        public static MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder builder() {
            return new MonthlyReportDTO.CategoryBreakdown.CategoryBreakdownBuilder();
        }

        public String getCategory() {
            return this.category;
        }

        public BigDecimal getAmount() {
            return this.amount;
        }

        public long getTransactions() {
            return this.transactions;
        }

        public void setCategory(final String category) {
            this.category = category;
        }

        public void setAmount(final BigDecimal amount) {
            this.amount = amount;
        }

        public void setTransactions(final long transactions) {
            this.transactions = transactions;
        }

        @java.lang.Override

        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof MonthlyReportDTO.CategoryBreakdown)) return false;
            final MonthlyReportDTO.CategoryBreakdown other = (MonthlyReportDTO.CategoryBreakdown) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getTransactions() != other.getTransactions()) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$amount = this.getAmount();
            final java.lang.Object other$amount = other.getAmount();
            if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
            return true;
        }

        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof MonthlyReportDTO.CategoryBreakdown;
        }

        @java.lang.Override

        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $transactions = this.getTransactions();
            result = result * PRIME + (int) ($transactions >>> 32 ^ $transactions);
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $amount = this.getAmount();
            result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
            return result;
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MonthlyReportDTO.CategoryBreakdown(category=" + this.getCategory() + ", amount=" + this.getAmount() + ", transactions=" + this.getTransactions() + ")";
        }

        public CategoryBreakdown() {
        }

        public CategoryBreakdown(final String category, final BigDecimal amount, final long transactions) {
            this.category = category;
            this.amount = amount;
            this.transactions = transactions;
        }
    }

    public static class MonthlyReportDTOBuilder {

        private int year;

        private String reportScope;

        private List<MonthEntry> months;

        private BigDecimal totalInvestedInPeriod;

        private long totalTransactionsInPeriod;

        private long activeFundsInPeriod;

        MonthlyReportDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder year(final int year) {
            this.year = year;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder reportScope(final String reportScope) {
            this.reportScope = reportScope;
            return this;
        }

        /**
         * One entry per month that has data
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder months(final List<MonthEntry> months) {
            this.months = months;
            return this;
        }

        /**
         * Summary totals across the entire report period
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder totalInvestedInPeriod(final BigDecimal totalInvestedInPeriod) {
            this.totalInvestedInPeriod = totalInvestedInPeriod;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder totalTransactionsInPeriod(final long totalTransactionsInPeriod) {
            this.totalTransactionsInPeriod = totalTransactionsInPeriod;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MonthlyReportDTO.MonthlyReportDTOBuilder activeFundsInPeriod(final long activeFundsInPeriod) {
            this.activeFundsInPeriod = activeFundsInPeriod;
            return this;
        }

        public MonthlyReportDTO build() {
            return new MonthlyReportDTO(this.year, this.reportScope, this.months, this.totalInvestedInPeriod, this.totalTransactionsInPeriod, this.activeFundsInPeriod);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MonthlyReportDTO.MonthlyReportDTOBuilder(year=" + this.year + ", reportScope=" + this.reportScope + ", months=" + this.months + ", totalInvestedInPeriod=" + this.totalInvestedInPeriod + ", totalTransactionsInPeriod=" + this.totalTransactionsInPeriod + ", activeFundsInPeriod=" + this.activeFundsInPeriod + ")";
        }
    }

    public static MonthlyReportDTO.MonthlyReportDTOBuilder builder() {
        return new MonthlyReportDTO.MonthlyReportDTOBuilder();
    }

    public int getYear() {
        return this.year;
    }

    public String getReportScope() {
        return this.reportScope;
    }

    /**
     * One entry per month that has data
     */

    public List<MonthEntry> getMonths() {
        return this.months;
    }

    /**
     * Summary totals across the entire report period
     */

    public BigDecimal getTotalInvestedInPeriod() {
        return this.totalInvestedInPeriod;
    }

    public long getTotalTransactionsInPeriod() {
        return this.totalTransactionsInPeriod;
    }

    public long getActiveFundsInPeriod() {
        return this.activeFundsInPeriod;
    }

    public void setYear(final int year) {
        this.year = year;
    }

    public void setReportScope(final String reportScope) {
        this.reportScope = reportScope;
    }

    /**
     * One entry per month that has data
     */

    public void setMonths(final List<MonthEntry> months) {
        this.months = months;
    }

    /**
     * Summary totals across the entire report period
     */

    public void setTotalInvestedInPeriod(final BigDecimal totalInvestedInPeriod) {
        this.totalInvestedInPeriod = totalInvestedInPeriod;
    }

    public void setTotalTransactionsInPeriod(final long totalTransactionsInPeriod) {
        this.totalTransactionsInPeriod = totalTransactionsInPeriod;
    }

    public void setActiveFundsInPeriod(final long activeFundsInPeriod) {
        this.activeFundsInPeriod = activeFundsInPeriod;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MonthlyReportDTO)) return false;
        final MonthlyReportDTO other = (MonthlyReportDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getYear() != other.getYear()) return false;
        if (this.getTotalTransactionsInPeriod() != other.getTotalTransactionsInPeriod()) return false;
        if (this.getActiveFundsInPeriod() != other.getActiveFundsInPeriod()) return false;
        final java.lang.Object this$reportScope = this.getReportScope();
        final java.lang.Object other$reportScope = other.getReportScope();
        if (this$reportScope == null ? other$reportScope != null : !this$reportScope.equals(other$reportScope)) return false;
        final java.lang.Object this$months = this.getMonths();
        final java.lang.Object other$months = other.getMonths();
        if (this$months == null ? other$months != null : !this$months.equals(other$months)) return false;
        final java.lang.Object this$totalInvestedInPeriod = this.getTotalInvestedInPeriod();
        final java.lang.Object other$totalInvestedInPeriod = other.getTotalInvestedInPeriod();
        if (this$totalInvestedInPeriod == null ? other$totalInvestedInPeriod != null : !this$totalInvestedInPeriod.equals(other$totalInvestedInPeriod)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MonthlyReportDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getYear();
        final long $totalTransactionsInPeriod = this.getTotalTransactionsInPeriod();
        result = result * PRIME + (int) ($totalTransactionsInPeriod >>> 32 ^ $totalTransactionsInPeriod);
        final long $activeFundsInPeriod = this.getActiveFundsInPeriod();
        result = result * PRIME + (int) ($activeFundsInPeriod >>> 32 ^ $activeFundsInPeriod);
        final java.lang.Object $reportScope = this.getReportScope();
        result = result * PRIME + ($reportScope == null ? 43 : $reportScope.hashCode());
        final java.lang.Object $months = this.getMonths();
        result = result * PRIME + ($months == null ? 43 : $months.hashCode());
        final java.lang.Object $totalInvestedInPeriod = this.getTotalInvestedInPeriod();
        result = result * PRIME + ($totalInvestedInPeriod == null ? 43 : $totalInvestedInPeriod.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "MonthlyReportDTO(year=" + this.getYear() + ", reportScope=" + this.getReportScope() + ", months=" + this.getMonths() + ", totalInvestedInPeriod=" + this.getTotalInvestedInPeriod() + ", totalTransactionsInPeriod=" + this.getTotalTransactionsInPeriod() + ", activeFundsInPeriod=" + this.getActiveFundsInPeriod() + ")";
    }

    public MonthlyReportDTO() {
    }

    /**
     * Creates a new {@code MonthlyReportDTO} instance.
     *
     * @param year
     * @param reportScope
     * @param months One entry per month that has data
     * @param totalInvestedInPeriod Summary totals across the entire report period
     * @param totalTransactionsInPeriod
     * @param activeFundsInPeriod
     */

    public MonthlyReportDTO(final int year, final String reportScope, final List<MonthEntry> months, final BigDecimal totalInvestedInPeriod, final long totalTransactionsInPeriod, final long activeFundsInPeriod) {
        this.year = year;
        this.reportScope = reportScope;
        this.months = months;
        this.totalInvestedInPeriod = totalInvestedInPeriod;
        this.totalTransactionsInPeriod = totalTransactionsInPeriod;
        this.activeFundsInPeriod = activeFundsInPeriod;
    }
}
