// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Outbound DTO representing a Mutual Fund returned to the client.
 * Does NOT expose the {@code investments} list or internal flags directly.
 */
public class MutualFundResponseDTO {
    private Long id;
    private String fundName;
    private String category;
    private String riskLevel;
    private BigDecimal returns;
    private BigDecimal nav;
    private String description;
    private boolean active;

    public static class MutualFundResponseDTOBuilder {

        private Long id;

        private String fundName;

        private String category;

        private String riskLevel;

        private BigDecimal returns;

        private BigDecimal nav;

        private String description;

        private boolean active;

        MutualFundResponseDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder returns(final BigDecimal returns) {
            this.returns = returns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder nav(final BigDecimal nav) {
            this.nav = nav;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MutualFundResponseDTO.MutualFundResponseDTOBuilder active(final boolean active) {
            this.active = active;
            return this;
        }

        public MutualFundResponseDTO build() {
            return new MutualFundResponseDTO(this.id, this.fundName, this.category, this.riskLevel, this.returns, this.nav, this.description, this.active);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MutualFundResponseDTO.MutualFundResponseDTOBuilder(id=" + this.id + ", fundName=" + this.fundName + ", category=" + this.category + ", riskLevel=" + this.riskLevel + ", returns=" + this.returns + ", nav=" + this.nav + ", description=" + this.description + ", active=" + this.active + ")";
        }
    }

    public static MutualFundResponseDTO.MutualFundResponseDTOBuilder builder() {
        return new MutualFundResponseDTO.MutualFundResponseDTOBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public String getFundName() {
        return this.fundName;
    }

    public String getCategory() {
        return this.category;
    }

    public String getRiskLevel() {
        return this.riskLevel;
    }

    public BigDecimal getReturns() {
        return this.returns;
    }

    public BigDecimal getNav() {
        return this.nav;
    }

    public String getDescription() {
        return this.description;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    public void setCategory(final String category) {
        this.category = category;
    }

    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public void setReturns(final BigDecimal returns) {
        this.returns = returns;
    }

    public void setNav(final BigDecimal nav) {
        this.nav = nav;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MutualFundResponseDTO)) return false;
        final MutualFundResponseDTO other = (MutualFundResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isActive() != other.isActive()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$returns = this.getReturns();
        final java.lang.Object other$returns = other.getReturns();
        if (this$returns == null ? other$returns != null : !this$returns.equals(other$returns)) return false;
        final java.lang.Object this$nav = this.getNav();
        final java.lang.Object other$nav = other.getNav();
        if (this$nav == null ? other$nav != null : !this$nav.equals(other$nav)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MutualFundResponseDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isActive() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $returns = this.getReturns();
        result = result * PRIME + ($returns == null ? 43 : $returns.hashCode());
        final java.lang.Object $nav = this.getNav();
        result = result * PRIME + ($nav == null ? 43 : $nav.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "MutualFundResponseDTO(id=" + this.getId() + ", fundName=" + this.getFundName() + ", category=" + this.getCategory() + ", riskLevel=" + this.getRiskLevel() + ", returns=" + this.getReturns() + ", nav=" + this.getNav() + ", description=" + this.getDescription() + ", active=" + this.isActive() + ")";
    }

    public MutualFundResponseDTO() {
    }

    public MutualFundResponseDTO(final Long id, final String fundName, final String category, final String riskLevel, final BigDecimal returns, final BigDecimal nav, final String description, final boolean active) {
        this.id = id;
        this.fundName = fundName;
        this.category = category;
        this.riskLevel = riskLevel;
        this.returns = returns;
        this.nav = nav;
        this.description = description;
        this.active = active;
    }
}
