// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Inbound DTO for creating or updating a Mutual Fund.
 *
 * All fields except {@code description} are mandatory.
 */
public class MutualFundRequestDTO {
    /**
     * Full name of the fund, e.g. "Axis Bluechip Fund"
     */
    private String fundName;
    /**
     * Category of the fund.
     * Accepted values: EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX
     */
    private String category;
    /**
     * Risk level.
     * Accepted values: LOW | MODERATE | HIGH | VERY_HIGH
     */
    private String riskLevel;
    /**
     * Annualised return percentage, e.g. 12.50 means 12.50 %
     */
    private BigDecimal returns;
    /**
     * Net Asset Value — current price per unit in INR.
     */
    private BigDecimal nav;
    /**
     * Optional description of the fund's investment objective / strategy.
     */
    private String description;

    public static class MutualFundRequestDTOBuilder {

        private String fundName;

        private String category;

        private String riskLevel;

        private BigDecimal returns;

        private BigDecimal nav;

        private String description;

        MutualFundRequestDTOBuilder() {
        }

        /**
         * Full name of the fund, e.g. "Axis Bluechip Fund"
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * Category of the fund.
         * Accepted values: EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * Risk level.
         * Accepted values: LOW | MODERATE | HIGH | VERY_HIGH
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * Annualised return percentage, e.g. 12.50 means 12.50 %
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder returns(final BigDecimal returns) {
            this.returns = returns;
            return this;
        }

        /**
         * Net Asset Value — current price per unit in INR.
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder nav(final BigDecimal nav) {
            this.nav = nav;
            return this;
        }

        /**
         * Optional description of the fund's investment objective / strategy.
         * @return {@code this}.
         */

        public MutualFundRequestDTO.MutualFundRequestDTOBuilder description(final String description) {
            this.description = description;
            return this;
        }

        public MutualFundRequestDTO build() {
            return new MutualFundRequestDTO(this.fundName, this.category, this.riskLevel, this.returns, this.nav, this.description);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MutualFundRequestDTO.MutualFundRequestDTOBuilder(fundName=" + this.fundName + ", category=" + this.category + ", riskLevel=" + this.riskLevel + ", returns=" + this.returns + ", nav=" + this.nav + ", description=" + this.description + ")";
        }
    }

    public static MutualFundRequestDTO.MutualFundRequestDTOBuilder builder() {
        return new MutualFundRequestDTO.MutualFundRequestDTOBuilder();
    }

    /**
     * Full name of the fund, e.g. "Axis Bluechip Fund"
     */

    public String getFundName() {
        return this.fundName;
    }

    /**
     * Category of the fund.
     * Accepted values: EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX
     */

    public String getCategory() {
        return this.category;
    }

    /**
     * Risk level.
     * Accepted values: LOW | MODERATE | HIGH | VERY_HIGH
     */

    public String getRiskLevel() {
        return this.riskLevel;
    }

    /**
     * Annualised return percentage, e.g. 12.50 means 12.50 %
     */

    public BigDecimal getReturns() {
        return this.returns;
    }

    /**
     * Net Asset Value — current price per unit in INR.
     */

    public BigDecimal getNav() {
        return this.nav;
    }

    /**
     * Optional description of the fund's investment objective / strategy.
     */

    public String getDescription() {
        return this.description;
    }

    /**
     * Full name of the fund, e.g. "Axis Bluechip Fund"
     */

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    /**
     * Category of the fund.
     * Accepted values: EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX
     */

    public void setCategory(final String category) {
        this.category = category;
    }

    /**
     * Risk level.
     * Accepted values: LOW | MODERATE | HIGH | VERY_HIGH
     */

    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * Annualised return percentage, e.g. 12.50 means 12.50 %
     */

    public void setReturns(final BigDecimal returns) {
        this.returns = returns;
    }

    /**
     * Net Asset Value — current price per unit in INR.
     */

    public void setNav(final BigDecimal nav) {
        this.nav = nav;
    }

    /**
     * Optional description of the fund's investment objective / strategy.
     */

    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MutualFundRequestDTO)) return false;
        final MutualFundRequestDTO other = (MutualFundRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$returns = this.getReturns();
        final java.lang.Object other$returns = other.getReturns();
        if (this$returns == null ? other$returns != null : !this$returns.equals(other$returns)) return false;
        final java.lang.Object this$nav = this.getNav();
        final java.lang.Object other$nav = other.getNav();
        if (this$nav == null ? other$nav != null : !this$nav.equals(other$nav)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MutualFundRequestDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $returns = this.getReturns();
        result = result * PRIME + ($returns == null ? 43 : $returns.hashCode());
        final java.lang.Object $nav = this.getNav();
        result = result * PRIME + ($nav == null ? 43 : $nav.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "MutualFundRequestDTO(fundName=" + this.getFundName() + ", category=" + this.getCategory() + ", riskLevel=" + this.getRiskLevel() + ", returns=" + this.getReturns() + ", nav=" + this.getNav() + ", description=" + this.getDescription() + ")";
    }

    public MutualFundRequestDTO() {
    }

    /**
     * Creates a new {@code MutualFundRequestDTO} instance.
     *
     * @param fundName Full name of the fund, e.g. "Axis Bluechip Fund"
     * @param category Category of the fund.
     * Accepted values: EQUITY | DEBT | HYBRID | LIQUID | ELSS | INDEX
     * @param riskLevel Risk level.
     * Accepted values: LOW | MODERATE | HIGH | VERY_HIGH
     * @param returns Annualised return percentage, e.g. 12.50 means 12.50 %
     * @param nav Net Asset Value — current price per unit in INR.
     * @param description Optional description of the fund's investment objective / strategy.
     */

    public MutualFundRequestDTO(final String fundName, final String category, final String riskLevel, final BigDecimal returns, final BigDecimal nav, final String description) {
        this.fundName = fundName;
        this.category = category;
        this.riskLevel = riskLevel;
        this.returns = returns;
        this.nav = nav;
        this.description = description;
    }
}
