// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.time.LocalDate;

/**
 * Represents a fund recommendation posted by an ADVISOR.
 *
 * Fields
 * ------
 * fundId      – the fund being recommended
 * fundName    – denormalised name for display
 * advisorId   – the ADVISOR user's ID
 * advisorName – denormalised name for display
 * rationale   – free-text justification / analysis
 * action      – BUY | HOLD | SELL
 * targetNav   – price target the advisor expects the fund to reach
 * date        – date the recommendation was issued
 */
public class RecommendationDTO {
    private Long fundId;
    private String fundName;
    private Long advisorId;
    private String advisorName;
    private String rationale;
    private String action; // BUY | HOLD | SELL
    private String riskLevel;
    private String category;
    private double returns;
    private LocalDate date;

    public static class RecommendationDTOBuilder {

        private Long fundId;

        private String fundName;

        private Long advisorId;

        private String advisorName;

        private String rationale;

        private String action;

        private String riskLevel;

        private String category;

        private double returns;

        private LocalDate date;

        RecommendationDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder fundId(final Long fundId) {
            this.fundId = fundId;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder advisorId(final Long advisorId) {
            this.advisorId = advisorId;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder advisorName(final String advisorName) {
            this.advisorName = advisorName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder rationale(final String rationale) {
            this.rationale = rationale;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder action(final String action) {
            this.action = action;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder returns(final double returns) {
            this.returns = returns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RecommendationDTO.RecommendationDTOBuilder date(final LocalDate date) {
            this.date = date;
            return this;
        }

        public RecommendationDTO build() {
            return new RecommendationDTO(this.fundId, this.fundName, this.advisorId, this.advisorName, this.rationale, this.action, this.riskLevel, this.category, this.returns, this.date);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "RecommendationDTO.RecommendationDTOBuilder(fundId=" + this.fundId + ", fundName=" + this.fundName + ", advisorId=" + this.advisorId + ", advisorName=" + this.advisorName + ", rationale=" + this.rationale + ", action=" + this.action + ", riskLevel=" + this.riskLevel + ", category=" + this.category + ", returns=" + this.returns + ", date=" + this.date + ")";
        }
    }

    public static RecommendationDTO.RecommendationDTOBuilder builder() {
        return new RecommendationDTO.RecommendationDTOBuilder();
    }

    public Long getFundId() {
        return this.fundId;
    }

    public String getFundName() {
        return this.fundName;
    }

    public Long getAdvisorId() {
        return this.advisorId;
    }

    public String getAdvisorName() {
        return this.advisorName;
    }

    public String getRationale() {
        return this.rationale;
    }

    public String getAction() {
        return this.action;
    }

    public String getRiskLevel() {
        return this.riskLevel;
    }

    public String getCategory() {
        return this.category;
    }

    public double getReturns() {
        return this.returns;
    }

    public LocalDate getDate() {
        return this.date;
    }

    public void setFundId(final Long fundId) {
        this.fundId = fundId;
    }

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    public void setAdvisorId(final Long advisorId) {
        this.advisorId = advisorId;
    }

    public void setAdvisorName(final String advisorName) {
        this.advisorName = advisorName;
    }

    public void setRationale(final String rationale) {
        this.rationale = rationale;
    }

    public void setAction(final String action) {
        this.action = action;
    }

    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public void setCategory(final String category) {
        this.category = category;
    }

    public void setReturns(final double returns) {
        this.returns = returns;
    }

    public void setDate(final LocalDate date) {
        this.date = date;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RecommendationDTO)) return false;
        final RecommendationDTO other = (RecommendationDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getReturns(), other.getReturns()) != 0) return false;
        final java.lang.Object this$fundId = this.getFundId();
        final java.lang.Object other$fundId = other.getFundId();
        if (this$fundId == null ? other$fundId != null : !this$fundId.equals(other$fundId)) return false;
        final java.lang.Object this$advisorId = this.getAdvisorId();
        final java.lang.Object other$advisorId = other.getAdvisorId();
        if (this$advisorId == null ? other$advisorId != null : !this$advisorId.equals(other$advisorId)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$advisorName = this.getAdvisorName();
        final java.lang.Object other$advisorName = other.getAdvisorName();
        if (this$advisorName == null ? other$advisorName != null : !this$advisorName.equals(other$advisorName)) return false;
        final java.lang.Object this$rationale = this.getRationale();
        final java.lang.Object other$rationale = other.getRationale();
        if (this$rationale == null ? other$rationale != null : !this$rationale.equals(other$rationale)) return false;
        final java.lang.Object this$action = this.getAction();
        final java.lang.Object other$action = other.getAction();
        if (this$action == null ? other$action != null : !this$action.equals(other$action)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RecommendationDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $returns = java.lang.Double.doubleToLongBits(this.getReturns());
        result = result * PRIME + (int) ($returns >>> 32 ^ $returns);
        final java.lang.Object $fundId = this.getFundId();
        result = result * PRIME + ($fundId == null ? 43 : $fundId.hashCode());
        final java.lang.Object $advisorId = this.getAdvisorId();
        result = result * PRIME + ($advisorId == null ? 43 : $advisorId.hashCode());
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $advisorName = this.getAdvisorName();
        result = result * PRIME + ($advisorName == null ? 43 : $advisorName.hashCode());
        final java.lang.Object $rationale = this.getRationale();
        result = result * PRIME + ($rationale == null ? 43 : $rationale.hashCode());
        final java.lang.Object $action = this.getAction();
        result = result * PRIME + ($action == null ? 43 : $action.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "RecommendationDTO(fundId=" + this.getFundId() + ", fundName=" + this.getFundName() + ", advisorId=" + this.getAdvisorId() + ", advisorName=" + this.getAdvisorName() + ", rationale=" + this.getRationale() + ", action=" + this.getAction() + ", riskLevel=" + this.getRiskLevel() + ", category=" + this.getCategory() + ", returns=" + this.getReturns() + ", date=" + this.getDate() + ")";
    }

    public RecommendationDTO() {
    }

    public RecommendationDTO(final Long fundId, final String fundName, final Long advisorId, final String advisorName, final String rationale, final String action, final String riskLevel, final String category, final double returns, final LocalDate date) {
        this.fundId = fundId;
        this.fundName = fundName;
        this.advisorId = advisorId;
        this.advisorName = advisorName;
        this.rationale = rationale;
        this.action = action;
        this.riskLevel = riskLevel;
        this.category = category;
        this.returns = returns;
        this.date = date;
    }
}
