// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

/**
 * Inbound DTO for user registration.
 *
 * Maps to {@code User} entity fields:
 *   name | email | password | role
 */
public class RegisterRequestDTO {
    /**
     * Full display name, e.g. "John Smith"
     */
    private String name;
    /**
     * Email address — used as login credential
     */
    private String email;
    /**
     * Plain-text password (will be BCrypt-hashed before storage)
     */
    private String password;
    /**
     * Optional role: ADMIN | INVESTOR | ADVISOR | ANALYST (defaults to INVESTOR)
     */
    private String role;

    public static class RegisterRequestDTOBuilder {

        private String name;

        private String email;

        private String password;

        private String role;

        RegisterRequestDTOBuilder() {
        }

        /**
         * Full display name, e.g. "John Smith"
         * @return {@code this}.
         */

        public RegisterRequestDTO.RegisterRequestDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * Email address — used as login credential
         * @return {@code this}.
         */

        public RegisterRequestDTO.RegisterRequestDTOBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * Plain-text password (will be BCrypt-hashed before storage)
         * @return {@code this}.
         */

        public RegisterRequestDTO.RegisterRequestDTOBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * Optional role: ADMIN | INVESTOR | ADVISOR | ANALYST (defaults to INVESTOR)
         * @return {@code this}.
         */

        public RegisterRequestDTO.RegisterRequestDTOBuilder role(final String role) {
            this.role = role;
            return this;
        }

        public RegisterRequestDTO build() {
            return new RegisterRequestDTO(this.name, this.email, this.password, this.role);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "RegisterRequestDTO.RegisterRequestDTOBuilder(name=" + this.name + ", email=" + this.email + ", password=" + this.password + ", role=" + this.role + ")";
        }
    }

    public static RegisterRequestDTO.RegisterRequestDTOBuilder builder() {
        return new RegisterRequestDTO.RegisterRequestDTOBuilder();
    }

    /**
     * Full display name, e.g. "John Smith"
     */

    public String getName() {
        return this.name;
    }

    /**
     * Email address — used as login credential
     */

    public String getEmail() {
        return this.email;
    }

    /**
     * Plain-text password (will be BCrypt-hashed before storage)
     */

    public String getPassword() {
        return this.password;
    }

    /**
     * Optional role: ADMIN | INVESTOR | ADVISOR | ANALYST (defaults to INVESTOR)
     */

    public String getRole() {
        return this.role;
    }

    /**
     * Full display name, e.g. "John Smith"
     */

    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Email address — used as login credential
     */

    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * Plain-text password (will be BCrypt-hashed before storage)
     */

    public void setPassword(final String password) {
        this.password = password;
    }

    /**
     * Optional role: ADMIN | INVESTOR | ADVISOR | ANALYST (defaults to INVESTOR)
     */

    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RegisterRequestDTO)) return false;
        final RegisterRequestDTO other = (RegisterRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RegisterRequestDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "RegisterRequestDTO(name=" + this.getName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", role=" + this.getRole() + ")";
    }

    public RegisterRequestDTO() {
    }

    /**
     * Creates a new {@code RegisterRequestDTO} instance.
     *
     * @param name Full display name, e.g. "John Smith"
     * @param email Email address — used as login credential
     * @param password Plain-text password (will be BCrypt-hashed before storage)
     * @param role Optional role: ADMIN | INVESTOR | ADVISOR | ANALYST (defaults to INVESTOR)
     */

    public RegisterRequestDTO(final String name, final String email, final String password, final String role) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }
}
