// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;
import java.util.List;

/**
 * Represents one bucket in the Risk vs Return comparison matrix.
 *
 * Each bucket = one risk level (LOW / MODERATE / HIGH / VERY_HIGH)
 * with aggregated return statistics and individual fund breakdowns.
 */
public class RiskReturnDTO {
    private String riskLevel; // LOW | MODERATE | HIGH | VERY_HIGH
    private long fundCount; // Number of active funds in this risk bucket
    private BigDecimal averageReturns; // Average annualised return for this bucket
    private BigDecimal minReturns; // Lowest return in this bucket
    private BigDecimal maxReturns; // Highest return in this bucket
    private BigDecimal medianReturns; // Median return (computed in-memory)
    /**
     * Individual funds in this risk bucket, sorted by returns descending
     */
    private List<FundSummary> funds;


    public static class FundSummary {
        private Long id;
        private String fundName;
        private BigDecimal returns;
        private BigDecimal nav;

        public static class FundSummaryBuilder {

            private Long id;

            private String fundName;

            private BigDecimal returns;

            private BigDecimal nav;

            FundSummaryBuilder() {
            }

            /**
             * @return {@code this}.
             */

            public RiskReturnDTO.FundSummary.FundSummaryBuilder id(final Long id) {
                this.id = id;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public RiskReturnDTO.FundSummary.FundSummaryBuilder fundName(final String fundName) {
                this.fundName = fundName;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public RiskReturnDTO.FundSummary.FundSummaryBuilder returns(final BigDecimal returns) {
                this.returns = returns;
                return this;
            }

            /**
             * @return {@code this}.
             */

            public RiskReturnDTO.FundSummary.FundSummaryBuilder nav(final BigDecimal nav) {
                this.nav = nav;
                return this;
            }

            public RiskReturnDTO.FundSummary build() {
                return new RiskReturnDTO.FundSummary(this.id, this.fundName, this.returns, this.nav);
            }

            @java.lang.Override

            public java.lang.String toString() {
                return "RiskReturnDTO.FundSummary.FundSummaryBuilder(id=" + this.id + ", fundName=" + this.fundName + ", returns=" + this.returns + ", nav=" + this.nav + ")";
            }
        }

        public static RiskReturnDTO.FundSummary.FundSummaryBuilder builder() {
            return new RiskReturnDTO.FundSummary.FundSummaryBuilder();
        }

        public Long getId() {
            return this.id;
        }

        public String getFundName() {
            return this.fundName;
        }

        public BigDecimal getReturns() {
            return this.returns;
        }

        public BigDecimal getNav() {
            return this.nav;
        }

        public void setId(final Long id) {
            this.id = id;
        }

        public void setFundName(final String fundName) {
            this.fundName = fundName;
        }

        public void setReturns(final BigDecimal returns) {
            this.returns = returns;
        }

        public void setNav(final BigDecimal nav) {
            this.nav = nav;
        }

        @java.lang.Override

        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof RiskReturnDTO.FundSummary)) return false;
            final RiskReturnDTO.FundSummary other = (RiskReturnDTO.FundSummary) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$fundName = this.getFundName();
            final java.lang.Object other$fundName = other.getFundName();
            if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
            final java.lang.Object this$returns = this.getReturns();
            final java.lang.Object other$returns = other.getReturns();
            if (this$returns == null ? other$returns != null : !this$returns.equals(other$returns)) return false;
            final java.lang.Object this$nav = this.getNav();
            final java.lang.Object other$nav = other.getNav();
            if (this$nav == null ? other$nav != null : !this$nav.equals(other$nav)) return false;
            return true;
        }

        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof RiskReturnDTO.FundSummary;
        }

        @java.lang.Override

        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $fundName = this.getFundName();
            result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
            final java.lang.Object $returns = this.getReturns();
            result = result * PRIME + ($returns == null ? 43 : $returns.hashCode());
            final java.lang.Object $nav = this.getNav();
            result = result * PRIME + ($nav == null ? 43 : $nav.hashCode());
            return result;
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "RiskReturnDTO.FundSummary(id=" + this.getId() + ", fundName=" + this.getFundName() + ", returns=" + this.getReturns() + ", nav=" + this.getNav() + ")";
        }

        public FundSummary() {
        }

        public FundSummary(final Long id, final String fundName, final BigDecimal returns, final BigDecimal nav) {
            this.id = id;
            this.fundName = fundName;
            this.returns = returns;
            this.nav = nav;
        }
    }

    public static class RiskReturnDTOBuilder {

        private String riskLevel;

        private long fundCount;

        private BigDecimal averageReturns;

        private BigDecimal minReturns;

        private BigDecimal maxReturns;

        private BigDecimal medianReturns;

        private List<FundSummary> funds;

        RiskReturnDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder fundCount(final long fundCount) {
            this.fundCount = fundCount;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder averageReturns(final BigDecimal averageReturns) {
            this.averageReturns = averageReturns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder minReturns(final BigDecimal minReturns) {
            this.minReturns = minReturns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder maxReturns(final BigDecimal maxReturns) {
            this.maxReturns = maxReturns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder medianReturns(final BigDecimal medianReturns) {
            this.medianReturns = medianReturns;
            return this;
        }

        /**
         * Individual funds in this risk bucket, sorted by returns descending
         * @return {@code this}.
         */

        public RiskReturnDTO.RiskReturnDTOBuilder funds(final List<FundSummary> funds) {
            this.funds = funds;
            return this;
        }

        public RiskReturnDTO build() {
            return new RiskReturnDTO(this.riskLevel, this.fundCount, this.averageReturns, this.minReturns, this.maxReturns, this.medianReturns, this.funds);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "RiskReturnDTO.RiskReturnDTOBuilder(riskLevel=" + this.riskLevel + ", fundCount=" + this.fundCount + ", averageReturns=" + this.averageReturns + ", minReturns=" + this.minReturns + ", maxReturns=" + this.maxReturns + ", medianReturns=" + this.medianReturns + ", funds=" + this.funds + ")";
        }
    }

    public static RiskReturnDTO.RiskReturnDTOBuilder builder() {
        return new RiskReturnDTO.RiskReturnDTOBuilder();
    }

    public String getRiskLevel() {
        return this.riskLevel;
    }

    public long getFundCount() {
        return this.fundCount;
    }

    public BigDecimal getAverageReturns() {
        return this.averageReturns;
    }

    public BigDecimal getMinReturns() {
        return this.minReturns;
    }

    public BigDecimal getMaxReturns() {
        return this.maxReturns;
    }

    public BigDecimal getMedianReturns() {
        return this.medianReturns;
    }

    /**
     * Individual funds in this risk bucket, sorted by returns descending
     */

    public List<FundSummary> getFunds() {
        return this.funds;
    }

    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public void setFundCount(final long fundCount) {
        this.fundCount = fundCount;
    }

    public void setAverageReturns(final BigDecimal averageReturns) {
        this.averageReturns = averageReturns;
    }

    public void setMinReturns(final BigDecimal minReturns) {
        this.minReturns = minReturns;
    }

    public void setMaxReturns(final BigDecimal maxReturns) {
        this.maxReturns = maxReturns;
    }

    public void setMedianReturns(final BigDecimal medianReturns) {
        this.medianReturns = medianReturns;
    }

    /**
     * Individual funds in this risk bucket, sorted by returns descending
     */

    public void setFunds(final List<FundSummary> funds) {
        this.funds = funds;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RiskReturnDTO)) return false;
        final RiskReturnDTO other = (RiskReturnDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getFundCount() != other.getFundCount()) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$averageReturns = this.getAverageReturns();
        final java.lang.Object other$averageReturns = other.getAverageReturns();
        if (this$averageReturns == null ? other$averageReturns != null : !this$averageReturns.equals(other$averageReturns)) return false;
        final java.lang.Object this$minReturns = this.getMinReturns();
        final java.lang.Object other$minReturns = other.getMinReturns();
        if (this$minReturns == null ? other$minReturns != null : !this$minReturns.equals(other$minReturns)) return false;
        final java.lang.Object this$maxReturns = this.getMaxReturns();
        final java.lang.Object other$maxReturns = other.getMaxReturns();
        if (this$maxReturns == null ? other$maxReturns != null : !this$maxReturns.equals(other$maxReturns)) return false;
        final java.lang.Object this$medianReturns = this.getMedianReturns();
        final java.lang.Object other$medianReturns = other.getMedianReturns();
        if (this$medianReturns == null ? other$medianReturns != null : !this$medianReturns.equals(other$medianReturns)) return false;
        final java.lang.Object this$funds = this.getFunds();
        final java.lang.Object other$funds = other.getFunds();
        if (this$funds == null ? other$funds != null : !this$funds.equals(other$funds)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RiskReturnDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $fundCount = this.getFundCount();
        result = result * PRIME + (int) ($fundCount >>> 32 ^ $fundCount);
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $averageReturns = this.getAverageReturns();
        result = result * PRIME + ($averageReturns == null ? 43 : $averageReturns.hashCode());
        final java.lang.Object $minReturns = this.getMinReturns();
        result = result * PRIME + ($minReturns == null ? 43 : $minReturns.hashCode());
        final java.lang.Object $maxReturns = this.getMaxReturns();
        result = result * PRIME + ($maxReturns == null ? 43 : $maxReturns.hashCode());
        final java.lang.Object $medianReturns = this.getMedianReturns();
        result = result * PRIME + ($medianReturns == null ? 43 : $medianReturns.hashCode());
        final java.lang.Object $funds = this.getFunds();
        result = result * PRIME + ($funds == null ? 43 : $funds.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "RiskReturnDTO(riskLevel=" + this.getRiskLevel() + ", fundCount=" + this.getFundCount() + ", averageReturns=" + this.getAverageReturns() + ", minReturns=" + this.getMinReturns() + ", maxReturns=" + this.getMaxReturns() + ", medianReturns=" + this.getMedianReturns() + ", funds=" + this.getFunds() + ")";
    }

    public RiskReturnDTO() {
    }

    /**
     * Creates a new {@code RiskReturnDTO} instance.
     *
     * @param riskLevel
     * @param fundCount
     * @param averageReturns
     * @param minReturns
     * @param maxReturns
     * @param medianReturns
     * @param funds Individual funds in this risk bucket, sorted by returns descending
     */

    public RiskReturnDTO(final String riskLevel, final long fundCount, final BigDecimal averageReturns, final BigDecimal minReturns, final BigDecimal maxReturns, final BigDecimal medianReturns, final List<FundSummary> funds) {
        this.riskLevel = riskLevel;
        this.fundCount = fundCount;
        this.averageReturns = averageReturns;
        this.minReturns = minReturns;
        this.maxReturns = maxReturns;
        this.medianReturns = medianReturns;
        this.funds = funds;
    }
}
