// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Represents a top-performing mutual fund entry in the analytics response.
 */
public class TopFundDTO {
    private Long id;
    private String fundName;
    private String category;
    private String riskLevel;
    private BigDecimal returns; // Annualised return %
    private BigDecimal nav;
    private BigDecimal navGrowth; // (currentNAV - purchaseNAV) / purchaseNAV * 100  — approx
    private Long totalInvestors; // Number of users who invested in this fund
    private BigDecimal totalAum; // Total amount invested across all users (platform AUM)
    private int rank; // 1 = best

    public static class TopFundDTOBuilder {

        private Long id;

        private String fundName;

        private String category;

        private String riskLevel;

        private BigDecimal returns;

        private BigDecimal nav;

        private BigDecimal navGrowth;

        private Long totalInvestors;

        private BigDecimal totalAum;

        private int rank;

        TopFundDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder fundName(final String fundName) {
            this.fundName = fundName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder returns(final BigDecimal returns) {
            this.returns = returns;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder nav(final BigDecimal nav) {
            this.nav = nav;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder navGrowth(final BigDecimal navGrowth) {
            this.navGrowth = navGrowth;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder totalInvestors(final Long totalInvestors) {
            this.totalInvestors = totalInvestors;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder totalAum(final BigDecimal totalAum) {
            this.totalAum = totalAum;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public TopFundDTO.TopFundDTOBuilder rank(final int rank) {
            this.rank = rank;
            return this;
        }

        public TopFundDTO build() {
            return new TopFundDTO(this.id, this.fundName, this.category, this.riskLevel, this.returns, this.nav, this.navGrowth, this.totalInvestors, this.totalAum, this.rank);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "TopFundDTO.TopFundDTOBuilder(id=" + this.id + ", fundName=" + this.fundName + ", category=" + this.category + ", riskLevel=" + this.riskLevel + ", returns=" + this.returns + ", nav=" + this.nav + ", navGrowth=" + this.navGrowth + ", totalInvestors=" + this.totalInvestors + ", totalAum=" + this.totalAum + ", rank=" + this.rank + ")";
        }
    }

    public static TopFundDTO.TopFundDTOBuilder builder() {
        return new TopFundDTO.TopFundDTOBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public String getFundName() {
        return this.fundName;
    }

    public String getCategory() {
        return this.category;
    }

    public String getRiskLevel() {
        return this.riskLevel;
    }

    public BigDecimal getReturns() {
        return this.returns;
    }

    public BigDecimal getNav() {
        return this.nav;
    }

    public BigDecimal getNavGrowth() {
        return this.navGrowth;
    }

    public Long getTotalInvestors() {
        return this.totalInvestors;
    }

    public BigDecimal getTotalAum() {
        return this.totalAum;
    }

    public int getRank() {
        return this.rank;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setFundName(final String fundName) {
        this.fundName = fundName;
    }

    public void setCategory(final String category) {
        this.category = category;
    }

    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public void setReturns(final BigDecimal returns) {
        this.returns = returns;
    }

    public void setNav(final BigDecimal nav) {
        this.nav = nav;
    }

    public void setNavGrowth(final BigDecimal navGrowth) {
        this.navGrowth = navGrowth;
    }

    public void setTotalInvestors(final Long totalInvestors) {
        this.totalInvestors = totalInvestors;
    }

    public void setTotalAum(final BigDecimal totalAum) {
        this.totalAum = totalAum;
    }

    public void setRank(final int rank) {
        this.rank = rank;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TopFundDTO)) return false;
        final TopFundDTO other = (TopFundDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getRank() != other.getRank()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$totalInvestors = this.getTotalInvestors();
        final java.lang.Object other$totalInvestors = other.getTotalInvestors();
        if (this$totalInvestors == null ? other$totalInvestors != null : !this$totalInvestors.equals(other$totalInvestors)) return false;
        final java.lang.Object this$fundName = this.getFundName();
        final java.lang.Object other$fundName = other.getFundName();
        if (this$fundName == null ? other$fundName != null : !this$fundName.equals(other$fundName)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$returns = this.getReturns();
        final java.lang.Object other$returns = other.getReturns();
        if (this$returns == null ? other$returns != null : !this$returns.equals(other$returns)) return false;
        final java.lang.Object this$nav = this.getNav();
        final java.lang.Object other$nav = other.getNav();
        if (this$nav == null ? other$nav != null : !this$nav.equals(other$nav)) return false;
        final java.lang.Object this$navGrowth = this.getNavGrowth();
        final java.lang.Object other$navGrowth = other.getNavGrowth();
        if (this$navGrowth == null ? other$navGrowth != null : !this$navGrowth.equals(other$navGrowth)) return false;
        final java.lang.Object this$totalAum = this.getTotalAum();
        final java.lang.Object other$totalAum = other.getTotalAum();
        if (this$totalAum == null ? other$totalAum != null : !this$totalAum.equals(other$totalAum)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TopFundDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getRank();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $totalInvestors = this.getTotalInvestors();
        result = result * PRIME + ($totalInvestors == null ? 43 : $totalInvestors.hashCode());
        final java.lang.Object $fundName = this.getFundName();
        result = result * PRIME + ($fundName == null ? 43 : $fundName.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $returns = this.getReturns();
        result = result * PRIME + ($returns == null ? 43 : $returns.hashCode());
        final java.lang.Object $nav = this.getNav();
        result = result * PRIME + ($nav == null ? 43 : $nav.hashCode());
        final java.lang.Object $navGrowth = this.getNavGrowth();
        result = result * PRIME + ($navGrowth == null ? 43 : $navGrowth.hashCode());
        final java.lang.Object $totalAum = this.getTotalAum();
        result = result * PRIME + ($totalAum == null ? 43 : $totalAum.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "TopFundDTO(id=" + this.getId() + ", fundName=" + this.getFundName() + ", category=" + this.getCategory() + ", riskLevel=" + this.getRiskLevel() + ", returns=" + this.getReturns() + ", nav=" + this.getNav() + ", navGrowth=" + this.getNavGrowth() + ", totalInvestors=" + this.getTotalInvestors() + ", totalAum=" + this.getTotalAum() + ", rank=" + this.getRank() + ")";
    }

    public TopFundDTO() {
    }

    public TopFundDTO(final Long id, final String fundName, final String category, final String riskLevel, final BigDecimal returns, final BigDecimal nav, final BigDecimal navGrowth, final Long totalInvestors, final BigDecimal totalAum, final int rank) {
        this.id = id;
        this.fundName = fundName;
        this.category = category;
        this.riskLevel = riskLevel;
        this.returns = returns;
        this.nav = nav;
        this.navGrowth = navGrowth;
        this.totalInvestors = totalInvestors;
        this.totalAum = totalAum;
        this.rank = rank;
    }
}
