// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

import java.math.BigDecimal;

/**
 * Outbound DTO for the total investment summary of a user.
 * Returned by the "Calculate total investment" API.
 */
public class TotalInvestmentDTO {
    /**
     * User ID
     */
    private Long userId;
    /**
     * Sum of all ACTIVE investment amounts
     */
    private BigDecimal totalActiveAmount;
    /**
     * Sum of ALL investments (any status)
     */
    private BigDecimal grandTotalAmount;
    /**
     * Current market value of ACTIVE portfolio (units × currentNav)
     */
    private BigDecimal currentPortfolioValue;
    /**
     * Overall gain/loss: currentPortfolioValue − totalActiveAmount
     */
    private BigDecimal overallGainLoss;
    /**
     * Overall gain/loss as a percentage
     */
    private BigDecimal overallGainLossPercent;
    /**
     * Number of distinct funds invested in (ACTIVE only)
     */
    private Long distinctFundsCount;
    /**
     * Total count of investment transactions
     */
    private Long totalTransactions;

    public static class TotalInvestmentDTOBuilder {

        private Long userId;

        private BigDecimal totalActiveAmount;

        private BigDecimal grandTotalAmount;

        private BigDecimal currentPortfolioValue;

        private BigDecimal overallGainLoss;

        private BigDecimal overallGainLossPercent;

        private Long distinctFundsCount;

        private Long totalTransactions;

        TotalInvestmentDTOBuilder() {
        }

        /**
         * User ID
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Sum of all ACTIVE investment amounts
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder totalActiveAmount(final BigDecimal totalActiveAmount) {
            this.totalActiveAmount = totalActiveAmount;
            return this;
        }

        /**
         * Sum of ALL investments (any status)
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder grandTotalAmount(final BigDecimal grandTotalAmount) {
            this.grandTotalAmount = grandTotalAmount;
            return this;
        }

        /**
         * Current market value of ACTIVE portfolio (units × currentNav)
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder currentPortfolioValue(final BigDecimal currentPortfolioValue) {
            this.currentPortfolioValue = currentPortfolioValue;
            return this;
        }

        /**
         * Overall gain/loss: currentPortfolioValue − totalActiveAmount
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder overallGainLoss(final BigDecimal overallGainLoss) {
            this.overallGainLoss = overallGainLoss;
            return this;
        }

        /**
         * Overall gain/loss as a percentage
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder overallGainLossPercent(final BigDecimal overallGainLossPercent) {
            this.overallGainLossPercent = overallGainLossPercent;
            return this;
        }

        /**
         * Number of distinct funds invested in (ACTIVE only)
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder distinctFundsCount(final Long distinctFundsCount) {
            this.distinctFundsCount = distinctFundsCount;
            return this;
        }

        /**
         * Total count of investment transactions
         * @return {@code this}.
         */

        public TotalInvestmentDTO.TotalInvestmentDTOBuilder totalTransactions(final Long totalTransactions) {
            this.totalTransactions = totalTransactions;
            return this;
        }

        public TotalInvestmentDTO build() {
            return new TotalInvestmentDTO(this.userId, this.totalActiveAmount, this.grandTotalAmount, this.currentPortfolioValue, this.overallGainLoss, this.overallGainLossPercent, this.distinctFundsCount, this.totalTransactions);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "TotalInvestmentDTO.TotalInvestmentDTOBuilder(userId=" + this.userId + ", totalActiveAmount=" + this.totalActiveAmount + ", grandTotalAmount=" + this.grandTotalAmount + ", currentPortfolioValue=" + this.currentPortfolioValue + ", overallGainLoss=" + this.overallGainLoss + ", overallGainLossPercent=" + this.overallGainLossPercent + ", distinctFundsCount=" + this.distinctFundsCount + ", totalTransactions=" + this.totalTransactions + ")";
        }
    }

    public static TotalInvestmentDTO.TotalInvestmentDTOBuilder builder() {
        return new TotalInvestmentDTO.TotalInvestmentDTOBuilder();
    }

    /**
     * User ID
     */

    public Long getUserId() {
        return this.userId;
    }

    /**
     * Sum of all ACTIVE investment amounts
     */

    public BigDecimal getTotalActiveAmount() {
        return this.totalActiveAmount;
    }

    /**
     * Sum of ALL investments (any status)
     */

    public BigDecimal getGrandTotalAmount() {
        return this.grandTotalAmount;
    }

    /**
     * Current market value of ACTIVE portfolio (units × currentNav)
     */

    public BigDecimal getCurrentPortfolioValue() {
        return this.currentPortfolioValue;
    }

    /**
     * Overall gain/loss: currentPortfolioValue − totalActiveAmount
     */

    public BigDecimal getOverallGainLoss() {
        return this.overallGainLoss;
    }

    /**
     * Overall gain/loss as a percentage
     */

    public BigDecimal getOverallGainLossPercent() {
        return this.overallGainLossPercent;
    }

    /**
     * Number of distinct funds invested in (ACTIVE only)
     */

    public Long getDistinctFundsCount() {
        return this.distinctFundsCount;
    }

    /**
     * Total count of investment transactions
     */

    public Long getTotalTransactions() {
        return this.totalTransactions;
    }

    /**
     * User ID
     */

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    /**
     * Sum of all ACTIVE investment amounts
     */

    public void setTotalActiveAmount(final BigDecimal totalActiveAmount) {
        this.totalActiveAmount = totalActiveAmount;
    }

    /**
     * Sum of ALL investments (any status)
     */

    public void setGrandTotalAmount(final BigDecimal grandTotalAmount) {
        this.grandTotalAmount = grandTotalAmount;
    }

    /**
     * Current market value of ACTIVE portfolio (units × currentNav)
     */

    public void setCurrentPortfolioValue(final BigDecimal currentPortfolioValue) {
        this.currentPortfolioValue = currentPortfolioValue;
    }

    /**
     * Overall gain/loss: currentPortfolioValue − totalActiveAmount
     */

    public void setOverallGainLoss(final BigDecimal overallGainLoss) {
        this.overallGainLoss = overallGainLoss;
    }

    /**
     * Overall gain/loss as a percentage
     */

    public void setOverallGainLossPercent(final BigDecimal overallGainLossPercent) {
        this.overallGainLossPercent = overallGainLossPercent;
    }

    /**
     * Number of distinct funds invested in (ACTIVE only)
     */

    public void setDistinctFundsCount(final Long distinctFundsCount) {
        this.distinctFundsCount = distinctFundsCount;
    }

    /**
     * Total count of investment transactions
     */

    public void setTotalTransactions(final Long totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TotalInvestmentDTO)) return false;
        final TotalInvestmentDTO other = (TotalInvestmentDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$distinctFundsCount = this.getDistinctFundsCount();
        final java.lang.Object other$distinctFundsCount = other.getDistinctFundsCount();
        if (this$distinctFundsCount == null ? other$distinctFundsCount != null : !this$distinctFundsCount.equals(other$distinctFundsCount)) return false;
        final java.lang.Object this$totalTransactions = this.getTotalTransactions();
        final java.lang.Object other$totalTransactions = other.getTotalTransactions();
        if (this$totalTransactions == null ? other$totalTransactions != null : !this$totalTransactions.equals(other$totalTransactions)) return false;
        final java.lang.Object this$totalActiveAmount = this.getTotalActiveAmount();
        final java.lang.Object other$totalActiveAmount = other.getTotalActiveAmount();
        if (this$totalActiveAmount == null ? other$totalActiveAmount != null : !this$totalActiveAmount.equals(other$totalActiveAmount)) return false;
        final java.lang.Object this$grandTotalAmount = this.getGrandTotalAmount();
        final java.lang.Object other$grandTotalAmount = other.getGrandTotalAmount();
        if (this$grandTotalAmount == null ? other$grandTotalAmount != null : !this$grandTotalAmount.equals(other$grandTotalAmount)) return false;
        final java.lang.Object this$currentPortfolioValue = this.getCurrentPortfolioValue();
        final java.lang.Object other$currentPortfolioValue = other.getCurrentPortfolioValue();
        if (this$currentPortfolioValue == null ? other$currentPortfolioValue != null : !this$currentPortfolioValue.equals(other$currentPortfolioValue)) return false;
        final java.lang.Object this$overallGainLoss = this.getOverallGainLoss();
        final java.lang.Object other$overallGainLoss = other.getOverallGainLoss();
        if (this$overallGainLoss == null ? other$overallGainLoss != null : !this$overallGainLoss.equals(other$overallGainLoss)) return false;
        final java.lang.Object this$overallGainLossPercent = this.getOverallGainLossPercent();
        final java.lang.Object other$overallGainLossPercent = other.getOverallGainLossPercent();
        if (this$overallGainLossPercent == null ? other$overallGainLossPercent != null : !this$overallGainLossPercent.equals(other$overallGainLossPercent)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TotalInvestmentDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $distinctFundsCount = this.getDistinctFundsCount();
        result = result * PRIME + ($distinctFundsCount == null ? 43 : $distinctFundsCount.hashCode());
        final java.lang.Object $totalTransactions = this.getTotalTransactions();
        result = result * PRIME + ($totalTransactions == null ? 43 : $totalTransactions.hashCode());
        final java.lang.Object $totalActiveAmount = this.getTotalActiveAmount();
        result = result * PRIME + ($totalActiveAmount == null ? 43 : $totalActiveAmount.hashCode());
        final java.lang.Object $grandTotalAmount = this.getGrandTotalAmount();
        result = result * PRIME + ($grandTotalAmount == null ? 43 : $grandTotalAmount.hashCode());
        final java.lang.Object $currentPortfolioValue = this.getCurrentPortfolioValue();
        result = result * PRIME + ($currentPortfolioValue == null ? 43 : $currentPortfolioValue.hashCode());
        final java.lang.Object $overallGainLoss = this.getOverallGainLoss();
        result = result * PRIME + ($overallGainLoss == null ? 43 : $overallGainLoss.hashCode());
        final java.lang.Object $overallGainLossPercent = this.getOverallGainLossPercent();
        result = result * PRIME + ($overallGainLossPercent == null ? 43 : $overallGainLossPercent.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "TotalInvestmentDTO(userId=" + this.getUserId() + ", totalActiveAmount=" + this.getTotalActiveAmount() + ", grandTotalAmount=" + this.getGrandTotalAmount() + ", currentPortfolioValue=" + this.getCurrentPortfolioValue() + ", overallGainLoss=" + this.getOverallGainLoss() + ", overallGainLossPercent=" + this.getOverallGainLossPercent() + ", distinctFundsCount=" + this.getDistinctFundsCount() + ", totalTransactions=" + this.getTotalTransactions() + ")";
    }

    public TotalInvestmentDTO() {
    }

    /**
     * Creates a new {@code TotalInvestmentDTO} instance.
     *
     * @param userId User ID
     * @param totalActiveAmount Sum of all ACTIVE investment amounts
     * @param grandTotalAmount Sum of ALL investments (any status)
     * @param currentPortfolioValue Current market value of ACTIVE portfolio (units × currentNav)
     * @param overallGainLoss Overall gain/loss: currentPortfolioValue − totalActiveAmount
     * @param overallGainLossPercent Overall gain/loss as a percentage
     * @param distinctFundsCount Number of distinct funds invested in (ACTIVE only)
     * @param totalTransactions Total count of investment transactions
     */

    public TotalInvestmentDTO(final Long userId, final BigDecimal totalActiveAmount, final BigDecimal grandTotalAmount, final BigDecimal currentPortfolioValue, final BigDecimal overallGainLoss, final BigDecimal overallGainLossPercent, final Long distinctFundsCount, final Long totalTransactions) {
        this.userId = userId;
        this.totalActiveAmount = totalActiveAmount;
        this.grandTotalAmount = grandTotalAmount;
        this.currentPortfolioValue = currentPortfolioValue;
        this.overallGainLoss = overallGainLoss;
        this.overallGainLossPercent = overallGainLossPercent;
        this.distinctFundsCount = distinctFundsCount;
        this.totalTransactions = totalTransactions;
    }
}
