// Generated by delombok at Tue Apr 07 22:43:40 IST 2026
package com.klu.dto;

/**
 * Outbound DTO representing a User.
 * Never exposes the password field.
 *
 * Fields match the updated {@code User} entity:
 *   id | name | email | role | enabled
 */
public class UserResponseDTO {
    private Long id;
    /**
     * Full display name (e.g. "John Smith")
     */
    private String name;
    /**
     * Email address – the unique login credential
     */
    private String email;
    /**
     * Role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */
    private String role;
    /**
     * false = account deactivated
     */
    private boolean enabled;

    public static class UserResponseDTOBuilder {

        private Long id;

        private String name;

        private String email;

        private String role;

        private boolean enabled;

        UserResponseDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public UserResponseDTO.UserResponseDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * Full display name (e.g. "John Smith")
         * @return {@code this}.
         */

        public UserResponseDTO.UserResponseDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * Email address – the unique login credential
         * @return {@code this}.
         */

        public UserResponseDTO.UserResponseDTOBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * Role: ADMIN | INVESTOR | ADVISOR | ANALYST
         * @return {@code this}.
         */

        public UserResponseDTO.UserResponseDTOBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * false = account deactivated
         * @return {@code this}.
         */

        public UserResponseDTO.UserResponseDTOBuilder enabled(final boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        public UserResponseDTO build() {
            return new UserResponseDTO(this.id, this.name, this.email, this.role, this.enabled);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "UserResponseDTO.UserResponseDTOBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", role=" + this.role + ", enabled=" + this.enabled + ")";
        }
    }

    public static UserResponseDTO.UserResponseDTOBuilder builder() {
        return new UserResponseDTO.UserResponseDTOBuilder();
    }

    public Long getId() {
        return this.id;
    }

    /**
     * Full display name (e.g. "John Smith")
     */

    public String getName() {
        return this.name;
    }

    /**
     * Email address – the unique login credential
     */

    public String getEmail() {
        return this.email;
    }

    /**
     * Role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */

    public String getRole() {
        return this.role;
    }

    /**
     * false = account deactivated
     */

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    /**
     * Full display name (e.g. "John Smith")
     */

    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Email address – the unique login credential
     */

    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * Role: ADMIN | INVESTOR | ADVISOR | ANALYST
     */

    public void setRole(final String role) {
        this.role = role;
    }

    /**
     * false = account deactivated
     */

    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserResponseDTO)) return false;
        final UserResponseDTO other = (UserResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isEnabled() != other.isEnabled()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserResponseDTO;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isEnabled() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "UserResponseDTO(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", role=" + this.getRole() + ", enabled=" + this.isEnabled() + ")";
    }

    public UserResponseDTO() {
    }

    /**
     * Creates a new {@code UserResponseDTO} instance.
     *
     * @param id
     * @param name Full display name (e.g. "John Smith")
     * @param email Email address – the unique login credential
     * @param role Role: ADMIN | INVESTOR | ADVISOR | ANALYST
     * @param enabled false = account deactivated
     */

    public UserResponseDTO(final Long id, final String name, final String email, final String role, final boolean enabled) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.role = role;
        this.enabled = enabled;
    }
}
